# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-07-13 22:47
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('monitoring', '0002_workersnapshot_message_count'),
    ]

    operations = [
        migrations.DeleteModel(
            name='MQSnapshot',
        ),
    ]
