# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-07-15 00:08
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('monitoring', '0003_delete_mqsnapshot'),
    ]

    operations = [
        migrations.AlterField(
            model_name='databasesnapshot',
            name='datetime_created',
            field=models.DateTimeField(),
        ),
        migrations.AlterField(
            model_name='readingserversnapshot',
            name='datetime_created',
            field=models.DateTimeField(),
        ),
        migrations.AlterField(
            model_name='webserversnapshot',
            name='datetime_created',
            field=models.DateTimeField(),
        ),
        migrations.AlterField(
            model_name='workersnapshot',
            name='datetime_created',
            field=models.DateTimeField(),
        ),
    ]
