# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-07-15 00:06
from __future__ import unicode_literals
from datetime import datetime

from django.db import migrations

from pytz import UTC


def round_datetimes(apps, schema_editor):
    for model_name in (
            'DatabaseSnapshot',
            'ReadingServerSnapshot',
            'WebServerSnapshot',
            'WorkerSnapshot'):
        model = apps.get_model('monitoring', model_name)
        for instance in model.objects.all():
            old_dt = instance.datetime_created
            new_dt = UTC.localize(
                datetime(old_dt.year, old_dt.month, old_dt.day, old_dt.hour,
                         old_dt.minute / 10 * 10))
            instance.datetime_created = new_dt
            instance.save()


class Migration(migrations.Migration):

    dependencies = [
        ('monitoring', '0004_auto_20160714_1908'),
    ]

    operations = [
        migrations.RunPython(round_datetimes)
    ]
