# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-07-16 15:09
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('monitoring', '0005_auto_20160714_1908'),
    ]

    operations = [
        migrations.AddField(
            model_name='databasesnapshot',
            name='load',
            field=models.FloatField(default=0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='readingserversnapshot',
            name='load',
            field=models.FloatField(default=0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='webserversnapshot',
            name='load',
            field=models.FloatField(default=0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='workersnapshot',
            name='load',
            field=models.FloatField(default=0),
            preserve_default=False,
        ),
    ]
