# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-07-16 15:09
from __future__ import unicode_literals

from django.db import migrations


def populate_load(apps, schema_editor):
    for model_name in (
            'DatabaseSnapshot',
            'ReadingServerSnapshot',
            'WebServerSnapshot',
            'WorkerSnapshot'):
        model = apps.get_model('monitoring', model_name)
        for instance in model.objects.all():
            instance.load = instance.medium_load
            instance.save()


class Migration(migrations.Migration):

    dependencies = [
        ('monitoring', '0006_auto_20160716_1009'),
    ]

    operations = [
        migrations.RunPython(populate_load)
    ]
