# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-07-16 15:12
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('monitoring', '0007_auto_20160716_1009'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='databasesnapshot',
            name='long_load',
        ),
        migrations.RemoveField(
            model_name='databasesnapshot',
            name='medium_load',
        ),
        migrations.RemoveField(
            model_name='databasesnapshot',
            name='short_load',
        ),
        migrations.RemoveField(
            model_name='readingserversnapshot',
            name='long_load',
        ),
        migrations.RemoveField(
            model_name='readingserversnapshot',
            name='medium_load',
        ),
        migrations.RemoveField(
            model_name='readingserversnapshot',
            name='short_load',
        ),
        migrations.RemoveField(
            model_name='webserversnapshot',
            name='long_load',
        ),
        migrations.RemoveField(
            model_name='webserversnapshot',
            name='medium_load',
        ),
        migrations.RemoveField(
            model_name='webserversnapshot',
            name='short_load',
        ),
        migrations.RemoveField(
            model_name='workersnapshot',
            name='long_load',
        ),
        migrations.RemoveField(
            model_name='workersnapshot',
            name='medium_load',
        ),
        migrations.RemoveField(
            model_name='workersnapshot',
            name='short_load',
        ),
    ]
