# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-07-16 15:38
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('monitoring', '0008_auto_20160716_1012'),
    ]

    operations = [
        migrations.AddField(
            model_name='readingserver',
            name='log_alias',
            field=models.CharField(default='', max_length=255, unique=True),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='readingserversnapshot',
            name='readings_received',
            field=models.PositiveIntegerField(default=0),
            preserve_default=False,
        ),
    ]
