# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-07-18 23:49
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('monitoring', '0011_auto_20160717_1554'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='scalabilitytest',
            options={'ordering': ('-date_started',)},
        ),
    ]
