# Generated by Django 3.0.8 on 2020-08-30 00:08

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0074_remove_patientprofile_doctors_name'),
    ]

    operations = [
        migrations.CreateModel(
            name='BloodPressureReading',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('datetime_received', models.DateTimeField(default=django.utils.timezone.now)),
                ('systolic_value', models.PositiveIntegerField()),
                ('diastolic_value', models.PositiveIntegerField()),
                ('patient_profile', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='blood_pressure_readings', to='accounts.PatientProfile')),
            ],
        ),
    ]
