# Generated by Django 3.0.8 on 2020-08-30 17:08

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0074_remove_patientprofile_doctors_name'),
        ('blood_pressure', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bloodpressurereading',
            name='datetime_received',
            field=models.DateTimeField(blank=True, default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='bloodpressurereading',
            name='patient_profile',
            field=models.ForeignKey(editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='blood_pressure_readings', to='accounts.PatientProfile'),
        ),
    ]
