# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-05-05 01:52
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('accounts', '0004_auto_20160229_1059'),
    ]

    operations = [
        migrations.CreateModel(
            name='AlertNotification',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('read', models.BooleanField(default=False)),
                ('sent_on', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='AlertTemplate',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('type', models.CharField(choices=[(b'reading_received', b'Reading Received'), (b'out_of_target_compliance', b'Out of Target Compliance'), (b'out_of_minimum_compliance', b'Out of Minimum Compliance'), (b'glucose_danger_range', b'Glucose Level in Danger Range'), (b'glucose_out_of_range', b'Glucose Level out of Target Range')], max_length=40)),
                ('message', models.TextField(default=b'')),
                ('recipient_type', models.CharField(choices=[(b'professional_recipient', b'Professional'), (b'patient_recipient', b'Patient')], max_length=100)),
                ('enabled', models.BooleanField(default=True)),
                ('send_by_text', models.BooleanField(default=False)),
                ('send_by_email', models.BooleanField(default=False)),
                ('send_by_message', models.BooleanField(default=True)),
                ('send_by_app', models.BooleanField(default=True)),
                ('group', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='alert_templates', to='accounts.GenesisGroup')),
            ],
        ),
        migrations.CreateModel(
            name='PatientAlert',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('type', models.CharField(choices=[(b'reading_received', b'Reading Received')], default=b'reading_received', max_length=40)),
                ('active', models.BooleanField(default=True)),
                ('last_triggered', models.DateTimeField(null=True)),
                ('phone_number', models.CharField(blank=True, max_length=100, null=True)),
                ('email', models.CharField(blank=True, max_length=255, null=True)),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='created_patientalerts', to=settings.AUTH_USER_MODEL)),
                ('patient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='my_patientalerts', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='PatientAlertNotificationLogEntry',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(choices=[(b'email', b'Email'), (b'text', b'Text')], max_length=255)),
                ('recipient', models.CharField(max_length=255)),
                ('datetime_created', models.DateTimeField(auto_now_add=True)),
                ('success', models.BooleanField()),
                ('alert', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='alerts.PatientAlert')),
            ],
        ),
        migrations.CreateModel(
            name='ProfessionalAlert',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('type', models.CharField(choices=[(b'reading_received', b'Reading Received')], default=b'reading_received', max_length=40)),
                ('active', models.BooleanField(default=True)),
                ('last_triggered', models.DateTimeField(null=True)),
                ('message', models.TextField(default=b'')),
                ('recipient_type', models.CharField(choices=[(b'professional_recipient', b'Professional'), (b'patient_recipient', b'Patient')], max_length=100)),
                ('send_by_text', models.BooleanField(default=False)),
                ('send_by_email', models.BooleanField(default=False)),
                ('send_by_app', models.BooleanField(default=False)),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='created_professionalalerts', to=settings.AUTH_USER_MODEL)),
                ('group', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='alerts', to='accounts.GenesisGroup')),
                ('patient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='my_professionalalerts', to=settings.AUTH_USER_MODEL)),
                ('professionals', models.ManyToManyField(related_name='alerts', to=settings.AUTH_USER_MODEL)),
                ('template', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='alerts.AlertTemplate')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.AddField(
            model_name='alertnotification',
            name='alert',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='alerts', to='alerts.ProfessionalAlert'),
        ),
        migrations.AddField(
            model_name='alertnotification',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='alert_notifications', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterUniqueTogether(
            name='alerttemplate',
            unique_together=set([('name', 'group')]),
        ),
    ]
