# Generated by Django 3.0.5 on 2020-06-01 04:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('alerts', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='alerttemplate',
            name='message',
            field=models.TextField(default=''),
        ),
        migrations.AlterField(
            model_name='alerttemplate',
            name='recipient_type',
            field=models.CharField(choices=[('professional_recipient', 'Professional'), ('patient_recipient', 'Patient')], max_length=100),
        ),
        migrations.AlterField(
            model_name='alerttemplate',
            name='type',
            field=models.CharField(choices=[('reading_received', 'Reading Received'), ('out_of_target_compliance', 'Out of Target Compliance'), ('out_of_minimum_compliance', 'Out of Minimum Compliance'), ('glucose_danger_range', 'Glucose Level in Danger Range'), ('glucose_out_of_range', 'Glucose Level out of Target Range')], max_length=40),
        ),
        migrations.AlterField(
            model_name='patientalert',
            name='type',
            field=models.CharField(choices=[('reading_received', 'Reading Received')], default='reading_received', max_length=40),
        ),
        migrations.AlterField(
            model_name='patientalertnotificationlogentry',
            name='type',
            field=models.CharField(choices=[('email', 'Email'), ('text', 'Text')], max_length=255),
        ),
        migrations.AlterField(
            model_name='professionalalert',
            name='message',
            field=models.TextField(default=''),
        ),
        migrations.AlterField(
            model_name='professionalalert',
            name='recipient_type',
            field=models.CharField(choices=[('professional_recipient', 'Professional'), ('patient_recipient', 'Patient')], max_length=100),
        ),
        migrations.AlterField(
            model_name='professionalalert',
            name='type',
            field=models.CharField(choices=[('reading_received', 'Reading Received')], default='reading_received', max_length=40),
        ),
    ]
