from django.conf.urls import url

from genesishealth.apps.orders.views.actions import (
    cancel, claim, create_problem, create_for_patient, edit, hold, resolve_problem, unhold, unlock)
from genesishealth.apps.orders.views.actions.shipment import (
    create as shipment_create,
    edit as shipment_edit,
    finalize as shipment_finalize,
    packing_list as shipment_packing_list,
    show_label as shipment_show_label)
from genesishealth.apps.orders.views.details import details
from genesishealth.apps.orders.views.main_tables import (
    index, open_orders, problem, hold as hold_table, worklist, shipments, canceled, shipping_history)
from genesishealth.apps.orders.views.reports import (
    business_partner_order_history,
    index as report_index,
    order_history,
    patient_order_history,
    projected_refills,
    rx_partner_order_history)


urlpatterns = [
    url(r'^$',
        index.main,
        name="index"),
    url(r'^open_orders/$',
        open_orders.main,
        name="open-orders"),
    url(r'^problem/$',
        problem.main,
        name="problem-orders"),
    url(r'^hold/$',
        hold_table.main,
        name="hold-orders"),
    url(r'^worklist/$',
        worklist.main,
        name="worklist"),
    url(r'^shipments/$',
        shipments.main,
        name="shipments"),
    url(r'^canceled/$',
        canceled.main,
        name="canceled"),
    url(r'^shipping_history/$',
        shipping_history.main,
        name="shipping-history"),
    url(r'^(?P<order_id>\d+)/$',
        details.main,
        name="details"),
    url(r'^(?P<order_id>\d+)/edit/$',
        edit.main,
        name="edit"),
    url(r'^(?P<order_id>\d+)/claim/$',
        claim.main,
        name="claim"),
    url(r'^(?P<order_id>\d+)/unhold/$',
        unhold.main,
        name="unhold"),
    url(r'^(?P<order_id>\d+)/resolve/$',
        resolve_problem.main,
        name="resolve-problem"),
    url(r'^(?P<order_id>\d+)/unlock/$',
        unlock.main,
        name="unlock"),
    url(r'^(?P<order_id>\d+)/cancel/$',
        cancel.main,
        name="cancel"),
    url(r'^(?P<order_id>\d+)/hold/$',
        hold.main,
        name="hold"),
    url(r'^(?P<order_id>\d+)/create_problem/$',
        create_problem.main,
        name="create-problem"),
    url(r'^(?P<order_id>\d+)/shipment/$',
        shipment_create.main,
        name="create-shipment"),
    url(r'^create_for_patient/(?P<patient_id>\d+)/$',
        create_for_patient.main,
        name="create-for-patient"),
    url(r'^shipment/(?P<shipment_id>\d+)/$',
        shipment_edit.main,
        name="edit-shipment"),
    url(r'^shipment/(?P<shipment_id>\d+)/finalize/$',
        shipment_finalize.main,
        name="finalize-shipment"),
    url(r'^shipment/(?P<shipment_id>\d+)/label/$',
        shipment_show_label.main,
        name="shipment-label"),
    url(r'^order/(?P<order_id>\d+)/contents/$',
        shipment_packing_list.main,
        name="shipment-packing-list"),
    url(r'^reports/$',
        report_index.main,
        name="reports-index"),
    url(r'^reports/patient_orders/(?P<patient_id>\d+)/$',
        patient_order_history.main,
        name="patient-order-report"),
    url(r'^reports/rx_partner_orders/(?P<rx_partner_id>\d+)/$',
        rx_partner_order_history.main,
        name="rx-partner-order-report"),
    url(r'^reports/business_partner_orders/(?P<partner_id>\d+)/$',
        business_partner_order_history.main,
        name="business-partner-order-report"),
    url(r'^reports/projected_refills/$',
        projected_refills.main,
        name="report-projected-refills"),
    url(r'^reports/order_history/$',
        order_history.main,
        name="order-history")
]
