# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-03-14 20:42
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import genesishealth.apps.reports.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='TemporaryDownload',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('valid_until', models.DateTimeField(default=genesishealth.apps.reports.models.tomorrow_dt, null=True)),
                ('content', models.TextField()),
                ('content_type', models.CharField(max_length=255)),
                ('filename', models.CharField(max_length=255)),
                ('for_user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='temporary_downloads', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
