# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2017-10-10 18:14
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('reports', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='temporarydownload',
            name='datetime_added',
            field=models.DateTimeField(auto_now_add=True, default=datetime.datetime(2017, 10, 10, 18, 14, 7, 621286, tzinfo=utc)),
            preserve_default=False,
        ),
    ]
