# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2017-10-10 18:19
from __future__ import unicode_literals

from django.db import migrations, models
import genesishealth.apps.reports.models


class Migration(migrations.Migration):

    dependencies = [
        ('reports', '0002_temporarydownload_datetime_added'),
    ]

    operations = [
        migrations.AlterField(
            model_name='temporarydownload',
            name='valid_until',
            field=models.DateTimeField(default=genesishealth.apps.reports.models.thirty_days_dt, null=True),
        ),
    ]
