# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-02-25 20:01
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='APILocation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('url', models.URLField()),
                ('type', models.CharField(choices=[(b'push_data', b'Push data'), (b'pull_data', b'Pull data'), (b'register', b'Register'), (b'unregister', b'Unregister')], max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='APILogRecord',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_inbound', models.BooleanField()),
                ('datetime', models.DateTimeField()),
                ('url', models.CharField(max_length=255)),
                ('action_type', models.CharField(choices=[(b'register_device', b'Register Device'), (b'unregister_device', b'Unregister Device'), (b'push_data', b'Push Data'), (b'pull_data', b'Pull Data')], max_length=255)),
                ('status', models.CharField(choices=[(b'connection_error', b'Failed: Connection Error'), (b'returned_error', b'Failed: Remote Server Returned Error'), (b'complete', b'Success')], max_length=255)),
                ('data', models.TextField(null=True)),
                ('response', models.TextField(null=True)),
            ],
        ),
        migrations.CreateModel(
            name='APIPartner',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, unique=True)),
                ('short_name', models.CharField(max_length=255, unique=True)),
                ('outgoing_username', models.CharField(blank=True, max_length=255, null=True)),
                ('outgoing_password', models.CharField(blank=True, max_length=255, null=True)),
                ('incoming_username', models.CharField(blank=True, max_length=255, null=True)),
                ('incoming_password', models.CharField(blank=True, max_length=255, null=True)),
                ('forward_readings', models.BooleanField()),
                ('send_register_updates', models.BooleanField()),
                ('use_verizon_output_format', models.BooleanField(default=False)),
                ('maximum_send_attempts', models.IntegerField(default=5)),
                ('api_version', models.CharField(choices=[(b'1.0', b'1.0'), (b'2.0', b'2.0')], default=b'1.0', max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='APIReadingForwardAttempt',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('datetime_created', models.DateTimeField(auto_now_add=True)),
                ('committed', models.BooleanField(default=False)),
                ('attempts', models.IntegerField(default=0)),
                ('partner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='forward_attempts', to='api.APIPartner')),
            ],
        ),
    ]
