# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-02-25 20:01
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('api', '0001_initial'),
        ('readings', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='apireadingforwardattempt',
            name='reading',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='forward_attempts', to='readings.GlucoseReading'),
        ),
        migrations.AddField(
            model_name='apilocation',
            name='partner',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='locations', to='api.APIPartner'),
        ),
        migrations.AlterUniqueTogether(
            name='apireadingforwardattempt',
            unique_together=set([('partner', 'reading')]),
        ),
        migrations.AlterUniqueTogether(
            name='apilocation',
            unique_together=set([('partner', 'type')]),
        ),
    ]
