# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-03-16 15:49
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_auto_20160225_1401'),
    ]

    operations = [
        migrations.AddField(
            model_name='apilogrecord',
            name='for_partner',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='api_log_records', to='api.APIPartner'),
        ),
        migrations.AddField(
            model_name='apilogrecord',
            name='reading',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='api_log_records', to='readings.GlucoseReading'),
        ),
    ]
