# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-05-16 00:56
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_auto_20160316_1049'),
    ]

    operations = [
        migrations.CreateModel(
            name='APIFlatfileConnection',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, unique=True)),
                ('host', models.CharField(max_length=255)),
                ('username', models.CharField(max_length=255)),
                ('password', models.CharField(max_length=255)),
                ('delivery_path', models.CharField(max_length=255)),
            ],
        ),
        migrations.AddField(
            model_name='apipartner',
            name='flatfile_connection',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='api.APIFlatfileConnection'),
        ),
    ]
