# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-05-22 20:27
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_auto_20160515_2046'),
    ]

    operations = [
        migrations.AddField(
            model_name='apiflatfileconnection',
            name='active',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='apiflatfileconnection',
            name='port',
            field=models.PositiveIntegerField(default=22),
        ),
    ]
