# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2019-01-13 23:46
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0006_auto_20160522_1527'),
    ]

    operations = [
        migrations.AddField(
            model_name='apipartner',
            name='outgoing_api_key',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='apipartner',
            name='api_version',
            field=models.CharField(choices=[(b'1.0', b'1.0'), (b'2.0', b'2.0'), (b'2.1', b'2.1')], default=b'1.0', max_length=255),
        ),
    ]
