# Generated by Django 3.0.5 on 2020-06-01 04:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('readings', '0005_auto_20200601_0444'),
        ('api', '0007_auto_20190113_1746'),
    ]

    operations = [
        migrations.AlterField(
            model_name='apilocation',
            name='type',
            field=models.CharField(choices=[('push_data', 'Push data'), ('pull_data', 'Pull data'), ('register', 'Register'), ('unregister', 'Unregister')], max_length=50),
        ),
        migrations.AlterField(
            model_name='apilogrecord',
            name='action_type',
            field=models.CharField(choices=[('register_device', 'Register Device'), ('unregister_device', 'Unregister Device'), ('push_data', 'Push Data'), ('pull_data', 'Pull Data')], max_length=255),
        ),
        migrations.AlterField(
            model_name='apilogrecord',
            name='for_partner',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='api_log_records', to='api.APIPartner'),
        ),
        migrations.AlterField(
            model_name='apilogrecord',
            name='reading',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='api_log_records', to='readings.GlucoseReading'),
        ),
        migrations.AlterField(
            model_name='apilogrecord',
            name='status',
            field=models.CharField(choices=[('connection_error', 'Failed: Connection Error'), ('returned_error', 'Failed: Remote Server Returned Error'), ('complete', 'Success')], max_length=255),
        ),
        migrations.AlterField(
            model_name='apipartner',
            name='api_version',
            field=models.CharField(choices=[('1.0', '1.0'), ('2.0', '2.0'), ('2.1', '2.1')], default='1.0', max_length=255),
        ),
        migrations.AlterField(
            model_name='apipartner',
            name='flatfile_connection',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='api.APIFlatfileConnection'),
        ),
    ]
