# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-02-23 20:09
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='QALogEntry',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('datetime_created', models.DateTimeField(auto_now_add=True)),
                ('reading_datetime', models.DateTimeField()),
                ('glucose_value', models.IntegerField()),
                ('meid', models.CharField(max_length=255)),
            ],
        ),
    ]
