# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-05-07 20:30
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('audit', '0001_initial'),
    ]

    database_operations = [
        migrations.AlterModelTable('QALogEntry', 'logs_qalogentry')
    ]

    state_operations = [
        migrations.DeleteModel('QALogEntry')
    ]

    operations = [
        migrations.SeparateDatabaseAndState(
            database_operations=database_operations,
            state_operations=state_operations)
    ]
