# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2018-07-28 13:11
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='NursingGroup',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, unique=True)),
                ('address', models.CharField(max_length=255)),
                ('address2', models.CharField(blank=True, max_length=255, null=True)),
                ('city', models.CharField(max_length=255)),
                ('zip', models.CharField(max_length=255)),
                ('state', models.CharField(max_length=255)),
                ('contact_name', models.CharField(max_length=255, null=True)),
                ('phone_number', models.CharField(max_length=255, null=True)),
                ('epc_identifier', models.CharField(max_length=255, null=True, unique=True)),
            ],
        ),
    ]
