# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-07-31 16:54
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dropdowns', '0004_auto_20160731_0946'),
    ]

    operations = [
        migrations.AlterField(
            model_name='communicationsubcategory',
            name='category',
            field=models.ManyToManyField(related_name='subcategories', to='dropdowns.CommunicationCategory'),
        ),
    ]
