# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-08-03 02:09
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dropdowns', '0007_auto_20160802_2043'),
        ('accounts', '0025_remove_patientcommunicationnote_replacements')
    ]

    database_operations = [
        migrations.AlterModelTable(
            'ProductType', 'products_producttype')
    ]

    state_operations = [
        migrations.DeleteModel('ProductType')
    ]

    operations = [
        migrations.SeparateDatabaseAndState(
            database_operations=database_operations,
            state_operations=state_operations)
    ]
