# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-08-12 23:37
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dropdowns', '0008_auto_20160802_2109'),
    ]

    operations = [
        migrations.AddField(
            model_name='communicationstatus',
            name='is_closed',
            field=models.BooleanField(default=False),
        ),
    ]
