# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2017-06-23 18:37
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dropdowns', '0012_auto_20170621_1942'),
    ]

    operations = [
        migrations.AddField(
            model_name='meterdisposition',
            name='is_problem',
            field=models.BooleanField(default=True),
        ),
    ]
