# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2017-06-23 18:59
from __future__ import unicode_literals

from django.db import migrations


def create_avail_disposition(apps, schema_editor):
    MeterDisposition = apps.get_model('dropdowns', 'MeterDisposition')
    MeterDisposition.objects.get_or_create(
        name="Available for Delivery", is_problem=False)


class Migration(migrations.Migration):

    dependencies = [
        ('dropdowns', '0013_meterdisposition_is_problem'),
    ]

    operations = [
        migrations.RunPython(create_avail_disposition)
    ]
