# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-10-25 21:41
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dropdowns', '0014_auto_20170623_1359'),
    ]

    operations = [
        migrations.CreateModel(
            name='OrderProblemCategory',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, unique=True)),
            ],
            options={
                'ordering': ('name',),
                'abstract': False,
            },
        ),
    ]
