# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2018-06-07 18:15
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dropdowns', '0015_orderproblemcategory'),
    ]

    operations = [
        migrations.AddField(
            model_name='communicationcategory',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
    ]
