# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-02-23 22:18
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='HealthInformation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('premeal_glucose_goal_minimum', models.IntegerField(default=70)),
                ('premeal_glucose_goal_maximum', models.IntegerField(default=130)),
                ('postmeal_glucose_goal_minimum', models.IntegerField(default=90)),
                ('postmeal_glucose_goal_maximum', models.IntegerField(default=180)),
                ('safe_zone_minimum', models.IntegerField(default=60)),
                ('safe_zone_maximum', models.IntegerField(default=250)),
                ('compliance_goal', models.IntegerField(default=3, help_text=b'Number of required daily tests')),
                ('minimum_compliance', models.IntegerField(default=1)),
                ('patient', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='HealthProfessionalTargets',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('premeal_glucose_goal_minimum', models.IntegerField(default=70)),
                ('premeal_glucose_goal_maximum', models.IntegerField(default=130)),
                ('postmeal_glucose_goal_minimum', models.IntegerField(default=90)),
                ('postmeal_glucose_goal_maximum', models.IntegerField(default=180)),
                ('safe_zone_minimum', models.IntegerField(default=60)),
                ('safe_zone_maximum', models.IntegerField(default=250)),
                ('compliance_goal', models.IntegerField(default=3, help_text=b'Number of required daily tests')),
                ('minimum_compliance', models.IntegerField(default=1)),
                ('patient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('professional', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='custom_health_targets', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AlterUniqueTogether(
            name='healthprofessionaltargets',
            unique_together=set([('patient', 'professional')]),
        ),
    ]
