# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-05-05 19:35
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('readings', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='bloodpressurereading',
            name='device',
        ),
        migrations.RemoveField(
            model_name='bloodpressurereading',
            name='patient',
        ),
        migrations.RemoveField(
            model_name='bloodpressurereadingnote',
            name='author',
        ),
        migrations.RemoveField(
            model_name='bloodpressurereadingnote',
            name='entry',
        ),
        migrations.RemoveField(
            model_name='weightreading',
            name='device',
        ),
        migrations.RemoveField(
            model_name='weightreading',
            name='patient',
        ),
        migrations.RemoveField(
            model_name='weightreadingnote',
            name='author',
        ),
        migrations.RemoveField(
            model_name='weightreadingnote',
            name='entry',
        ),
        migrations.DeleteModel(
            name='BloodPressureReading',
        ),
        migrations.DeleteModel(
            name='BloodPressureReadingNote',
        ),
        migrations.DeleteModel(
            name='WeightReading',
        ),
        migrations.DeleteModel(
            name='WeightReadingNote',
        ),
    ]
