# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-05-05 21:36
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('readings', '0002_auto_20160505_1435'),
    ]

    operations = [
        migrations.AddField(
            model_name='glucosereading',
            name='offset_adjusted',
            field=models.BooleanField(default=False),
        ),
    ]
