# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-07-01 12:40
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('readings', '0003_glucosereading_offset_adjusted'),
    ]

    operations = [
        migrations.AlterField(
            model_name='glucosereading',
            name='device',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='readings', to='gdrives.GDrive'),
        ),
        migrations.AlterField(
            model_name='glucosereading',
            name='manually_changed_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='glucosereading',
            name='patient',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='glucose_readings', to=settings.AUTH_USER_MODEL),
        ),
    ]
