# Generated by Django 3.0.5 on 2020-06-01 04:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('readings', '0004_auto_20160701_0740'),
    ]

    operations = [
        migrations.AlterField(
            model_name='glucosereading',
            name='measure_type',
            field=models.CharField(choices=[('normal', 'Normal'), ('before_meal', 'Before meal'), ('after_meal', 'After meal'), ('test_mode', 'TEST mode')], default='normal', max_length=100),
        ),
        migrations.AlterField(
            model_name='glucosereadingnote',
            name='content',
            field=models.TextField(blank=True, default=''),
        ),
    ]
