# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-02-25 20:01
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import genesishealth.apps.utils.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Company',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
            ],
            options={
                'verbose_name_plural': 'Companies',
            },
        ),
        migrations.CreateModel(
            name='Contact',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('salutation', models.CharField(blank=True, max_length=100, null=True)),
                ('first_name', models.CharField(blank=True, max_length=255, null=True)),
                ('middle_initial', models.CharField(blank=True, max_length=100, null=True)),
                ('last_name', models.CharField(blank=True, max_length=255, null=True)),
                ('address1', models.CharField(blank=True, max_length=255, null=True)),
                ('address2', models.CharField(blank=True, max_length=255, null=True)),
                ('city', models.CharField(blank=True, max_length=255, null=True)),
                ('state', models.CharField(blank=True, max_length=255, null=True)),
                ('zip', models.CharField(blank=True, max_length=255, null=True)),
                ('fax', models.CharField(blank=True, max_length=40, null=True)),
                ('email', models.EmailField(blank=True, max_length=254, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='DemoPatientProfile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reading_types', genesishealth.apps.utils.fields.SeparatedValuesField(default=b'glucose')),
                ('glucose_reading_interval', models.CharField(choices=[(b'weekly', b'Weekly'), (b'once_daily', b'Once a day'), (b'three_times_daily', b'Three times a day'), (b'five_times_daily', b'Five times a day')], default=b'five_times_daily', max_length=100)),
                ('average_premeal_glucose_level', models.IntegerField(default=100)),
                ('average_postmeal_glucose_level', models.IntegerField(default=100)),
                ('last_scheduled', models.DateTimeField(null=True)),
                ('active', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='DemoScheduledReading',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('value', models.IntegerField()),
                ('reading_datetime', models.DateTimeField()),
                ('fired', models.BooleanField(default=False)),
                ('premeal', models.BooleanField()),
                ('response', models.TextField(null=True)),
            ],
        ),
        migrations.CreateModel(
            name='GenesisGroup',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, unique=True)),
                ('group_type', models.CharField(choices=[(b'healthcare_provider', b'Healthcare Provider'), (b'insurance_administrator', b'Insurance Administrator'), (b'disease_management_organization', b'Disease Management Organization'), (b'pharmacist', b'Pharmacist')], max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='LoginRecord',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('datetime', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Message',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('subject', models.CharField(max_length=255)),
                ('content', models.TextField()),
                ('sent_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='MessageEntry',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('read', models.BooleanField(default=False)),
            ],
            options={
                'verbose_name': 'message entry',
                'verbose_name_plural': 'message entries',
            },
        ),
        migrations.CreateModel(
            name='Note',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.TextField()),
                ('date_created', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='PatientProfile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('last_touched', models.DateTimeField(null=True)),
                ('forgot_key', models.CharField(blank=True, editable=False, max_length=40, null=True)),
                ('forgot_key_updated', models.DateTimeField(blank=True, editable=False, null=True)),
                ('email_update_new', models.EmailField(blank=True, editable=False, max_length=254, null=True)),
                ('email_update_key', models.CharField(blank=True, editable=False, max_length=40, null=True)),
                ('email_update_key_updated', models.DateTimeField(blank=True, editable=False, null=True)),
                ('timezone_name', models.CharField(choices=[(b'US/Alaska', b'US/Alaska'), (b'US/Aleutian', b'US/Aleutian'), (b'US/Arizona', b'US/Arizona'), (b'US/Central', b'US/Central'), (b'US/East-Indiana', b'US/East-Indiana'), (b'US/Eastern', b'US/Eastern'), (b'US/Hawaii', b'US/Hawaii'), (b'US/Indiana-Starke', b'US/Indiana-Starke'), (b'US/Michigan', b'US/Michigan'), (b'US/Mountain', b'US/Mountain'), (b'US/Pacific', b'US/Pacific'), (b'US/Pacific-New', b'US/Pacific-New'), (b'US/Samoa', b'US/Samoa')], default=b'US/Central', max_length=255)),
                ('security_question1', models.CharField(blank=True, choices=[(b'grade_school', b'What Grade School did you attend?'), (b'mother_maiden', b"What is your mother's Maiden name?"), (b'grandmother_madien', b"What is your paternal grandmother's maiden name?"), (b'street', b'What Street did you grow up on?'), (b'eldest_sibling', b'In what year was your eldest sibling born?'), (b'hs_mascot', b'What was the name of your high school mascot?'), (b'favorite_pet', b'What is the name of your favorite pet?'), (b'favorite_food', b'What is your favorite food?'), (b'city_born', b'In what city where you born?')], max_length=100, null=True)),
                ('security_answer1', models.CharField(blank=True, max_length=100, null=True)),
                ('security_question2', models.CharField(blank=True, choices=[(b'grade_school', b'What Grade School did you attend?'), (b'mother_maiden', b"What is your mother's Maiden name?"), (b'grandmother_madien', b"What is your paternal grandmother's maiden name?"), (b'street', b'What Street did you grow up on?'), (b'eldest_sibling', b'In what year was your eldest sibling born?'), (b'hs_mascot', b'What was the name of your high school mascot?'), (b'favorite_pet', b'What is the name of your favorite pet?'), (b'favorite_food', b'What is your favorite food?'), (b'city_born', b'In what city where you born?')], max_length=100, null=True)),
                ('security_answer2', models.CharField(blank=True, max_length=100, null=True)),
                ('security_question3', models.CharField(blank=True, choices=[(b'grade_school', b'What Grade School did you attend?'), (b'mother_maiden', b"What is your mother's Maiden name?"), (b'grandmother_madien', b"What is your paternal grandmother's maiden name?"), (b'street', b'What Street did you grow up on?'), (b'eldest_sibling', b'In what year was your eldest sibling born?'), (b'hs_mascot', b'What was the name of your high school mascot?'), (b'favorite_pet', b'What is the name of your favorite pet?'), (b'favorite_food', b'What is your favorite food?'), (b'city_born', b'In what city where you born?')], max_length=100, null=True)),
                ('security_answer3', models.CharField(blank=True, max_length=100, null=True)),
                ('configured', models.BooleanField(default=False, editable=False)),
                ('is_reset_password', models.BooleanField(default=False, editable=False)),
                ('activation_key', models.CharField(blank=True, editable=False, max_length=40, null=True)),
                ('preferred_contact_method', models.CharField(choices=[(b'email', b'Email'), (b'phone', b'Phone')], max_length=255)),
                ('api_username', models.CharField(blank=True, max_length=255, null=True)),
                ('insurance_identifier', models.CharField(blank=True, editable=False, max_length=255, null=True)),
                ('gender', models.CharField(choices=[(b'male', b'Male'), (b'female', b'Female')], max_length=10)),
                ('date_of_birth', models.DateField(null=True)),
                ('demo_patient', models.BooleanField(default=False)),
                ('verizon_instance_id', models.CharField(max_length=255, null=True)),
                ('verizon_demo', models.BooleanField(default=False)),
                ('validation_status', models.CharField(choices=[(b'active', b'active'), (b'pending', b'pending')], editable=False, max_length=100, null=True)),
                ('is_scalability_user', models.BooleanField(default=False)),
                ('is_verizon_patient', models.BooleanField(default=False)),
                ('is_myghr_user', models.BooleanField(default=True)),
                ('company', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='patients', to='accounts.Company')),
                ('contact', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='+', to='accounts.Contact')),
                ('created_by_group', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='created_patients', to='accounts.GenesisGroup')),
                ('group', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='patients', to='accounts.GenesisGroup')),
            ],
        ),
        migrations.CreateModel(
            name='PatientStatisticRecord',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('readings_last_1', models.FloatField(null=True)),
                ('average_value_last_1', models.FloatField(null=True)),
                ('readings_last_7', models.FloatField(null=True)),
                ('average_value_last_7', models.FloatField(null=True)),
                ('readings_last_14', models.FloatField(null=True)),
                ('average_value_last_14', models.FloatField(null=True)),
                ('readings_last_30', models.FloatField(null=True)),
                ('average_value_last_30', models.FloatField(null=True)),
                ('readings_last_60', models.FloatField(null=True)),
                ('average_value_last_60', models.FloatField(null=True)),
                ('readings_last_90', models.FloatField(null=True)),
                ('average_value_last_90', models.FloatField(null=True)),
                ('profile', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='stats', to='accounts.PatientProfile')),
            ],
        ),
        migrations.CreateModel(
            name='Payor',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('contact', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='accounts.Contact')),
                ('group', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='payors', to='accounts.GenesisGroup')),
            ],
        ),
        migrations.CreateModel(
            name='PhoneNumber',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('phone', models.CharField(max_length=255)),
                ('is_cell', models.BooleanField()),
                ('is_contact', models.BooleanField()),
                ('contact', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='accounts.Contact')),
            ],
        ),
        migrations.CreateModel(
            name='ProfessionalProfile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('last_touched', models.DateTimeField(null=True)),
                ('forgot_key', models.CharField(blank=True, editable=False, max_length=40, null=True)),
                ('forgot_key_updated', models.DateTimeField(blank=True, editable=False, null=True)),
                ('email_update_new', models.EmailField(blank=True, editable=False, max_length=254, null=True)),
                ('email_update_key', models.CharField(blank=True, editable=False, max_length=40, null=True)),
                ('email_update_key_updated', models.DateTimeField(blank=True, editable=False, null=True)),
                ('timezone_name', models.CharField(choices=[(b'US/Alaska', b'US/Alaska'), (b'US/Aleutian', b'US/Aleutian'), (b'US/Arizona', b'US/Arizona'), (b'US/Central', b'US/Central'), (b'US/East-Indiana', b'US/East-Indiana'), (b'US/Eastern', b'US/Eastern'), (b'US/Hawaii', b'US/Hawaii'), (b'US/Indiana-Starke', b'US/Indiana-Starke'), (b'US/Michigan', b'US/Michigan'), (b'US/Mountain', b'US/Mountain'), (b'US/Pacific', b'US/Pacific'), (b'US/Pacific-New', b'US/Pacific-New'), (b'US/Samoa', b'US/Samoa')], default=b'US/Central', max_length=255)),
                ('security_question1', models.CharField(blank=True, choices=[(b'grade_school', b'What Grade School did you attend?'), (b'mother_maiden', b"What is your mother's Maiden name?"), (b'grandmother_madien', b"What is your paternal grandmother's maiden name?"), (b'street', b'What Street did you grow up on?'), (b'eldest_sibling', b'In what year was your eldest sibling born?'), (b'hs_mascot', b'What was the name of your high school mascot?'), (b'favorite_pet', b'What is the name of your favorite pet?'), (b'favorite_food', b'What is your favorite food?'), (b'city_born', b'In what city where you born?')], max_length=100, null=True)),
                ('security_answer1', models.CharField(blank=True, max_length=100, null=True)),
                ('security_question2', models.CharField(blank=True, choices=[(b'grade_school', b'What Grade School did you attend?'), (b'mother_maiden', b"What is your mother's Maiden name?"), (b'grandmother_madien', b"What is your paternal grandmother's maiden name?"), (b'street', b'What Street did you grow up on?'), (b'eldest_sibling', b'In what year was your eldest sibling born?'), (b'hs_mascot', b'What was the name of your high school mascot?'), (b'favorite_pet', b'What is the name of your favorite pet?'), (b'favorite_food', b'What is your favorite food?'), (b'city_born', b'In what city where you born?')], max_length=100, null=True)),
                ('security_answer2', models.CharField(blank=True, max_length=100, null=True)),
                ('security_question3', models.CharField(blank=True, choices=[(b'grade_school', b'What Grade School did you attend?'), (b'mother_maiden', b"What is your mother's Maiden name?"), (b'grandmother_madien', b"What is your paternal grandmother's maiden name?"), (b'street', b'What Street did you grow up on?'), (b'eldest_sibling', b'In what year was your eldest sibling born?'), (b'hs_mascot', b'What was the name of your high school mascot?'), (b'favorite_pet', b'What is the name of your favorite pet?'), (b'favorite_food', b'What is your favorite food?'), (b'city_born', b'In what city where you born?')], max_length=100, null=True)),
                ('security_answer3', models.CharField(blank=True, max_length=100, null=True)),
                ('configured', models.BooleanField(default=False, editable=False)),
                ('is_reset_password', models.BooleanField(default=False, editable=False)),
                ('contact', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='+', to='accounts.Contact')),
                ('parent_group', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='professionals', to='accounts.GenesisGroup')),
                ('patients', models.ManyToManyField(related_name='professionals', to='accounts.PatientProfile')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='professional_profile', to=settings.AUTH_USER_MODEL)),
                ('watch_list', models.ManyToManyField(related_name='watch_list_professionals', to='accounts.PatientProfile')),
            ],
        ),
        migrations.CreateModel(
            name='UserOption',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, unique=True)),
                ('display_name', models.CharField(max_length=255, unique=True)),
                ('default', models.CharField(max_length=255)),
                ('options', genesishealth.apps.utils.fields.SeparatedValuesField(null=True)),
                ('available_to_types', genesishealth.apps.utils.fields.SeparatedValuesField(default=[])),
            ],
        ),
        migrations.CreateModel(
            name='UserOptionEntry',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('value', models.CharField(max_length=255)),
                ('option', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='entries', to='accounts.UserOption')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='option_entries', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
