# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-02-25 20:01
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('api', '0001_initial'),
        ('accounts', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='patientprofile',
            name='partners',
            field=models.ManyToManyField(blank=True, related_name='patients', to='api.APIPartner'),
        ),
        migrations.AddField(
            model_name='patientprofile',
            name='user',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='patient_profile', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='note',
            name='author',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notes_authored', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='note',
            name='patient',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notes_about', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='messageentry',
            name='message',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='message_entries', to='accounts.Message'),
        ),
        migrations.AddField(
            model_name='messageentry',
            name='recipient',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='message',
            name='recipients',
            field=models.ManyToManyField(related_name='received_messages', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='message',
            name='sender',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='sent_messages', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='loginrecord',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='login_records', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='genesisgroup',
            name='contact',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='accounts.Contact'),
        ),
        migrations.AddField(
            model_name='demoscheduledreading',
            name='patient',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='scheduled_demo_readings', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='demopatientprofile',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='demo_profile', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='company',
            name='contact',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='accounts.Contact'),
        ),
        migrations.AddField(
            model_name='company',
            name='group',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='companies', to='accounts.GenesisGroup'),
        ),
        migrations.AddField(
            model_name='company',
            name='payor',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='companies', to='accounts.Payor'),
        ),
        migrations.AlterUniqueTogether(
            name='useroptionentry',
            unique_together=set([('option', 'user')]),
        ),
        migrations.AlterUniqueTogether(
            name='payor',
            unique_together=set([('name', 'group')]),
        ),
        migrations.AlterUniqueTogether(
            name='messageentry',
            unique_together=set([('recipient', 'message')]),
        ),
        migrations.AlterUniqueTogether(
            name='company',
            unique_together=set([('name', 'group')]),
        ),
    ]
