# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-02-25 20:02
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('readings', '0001_initial'),
        ('accounts', '0002_auto_20160225_1401'),
    ]

    operations = [
        migrations.AddField(
            model_name='patientprofile',
            name='last_reading',
            field=models.ForeignKey(editable=False, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='+', to='readings.GlucoseReading'),
        ),
    ]
