# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-02-29 16:59
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_patientprofile_last_reading'),
    ]

    operations = [
        migrations.AlterField(
            model_name='phonenumber',
            name='is_cell',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='phonenumber',
            name='is_contact',
            field=models.BooleanField(default=False),
        ),
    ]
