# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-05-15 23:49
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_auto_20160229_1059'),
    ]

    operations = [
        migrations.AddField(
            model_name='company',
            name='group_identifier',
            field=models.CharField(max_length=255, null=True),
        ),
    ]
