# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-06-24 03:18
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0006_auto_20160623_2158'),
    ]

    operations = [
        migrations.AddField(
            model_name='patientprofile',
            name='is_accepted_privacy',
            field=models.BooleanField(default=False, editable=False),
        ),
        migrations.AddField(
            model_name='professionalprofile',
            name='is_accepted_privacy',
            field=models.BooleanField(default=False, editable=False),
        ),
    ]
