# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-06-27 02:07
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('accounts', '0007_auto_20160623_2218'),
    ]

    operations = [
        migrations.CreateModel(
            name='ActivationRecord',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('effective_date', models.DateField()),
                ('reason', models.CharField(choices=[(b'business_associate', b'Business Associate'), (b'deceased', b'Deceased'), (b'pending_update', b'Hold Pending Info Update'), (b'inactive', b'Inactive'), (b'insurance_denied', b'Insurance Denied'), (b'package_returned', b'Package Returned'), (b'opted_out', b'Patient Opted Out'), (b'termed', b'Termed')], max_length=255)),
                ('datetime_created', models.DateTimeField(auto_now_add=True)),
                ('is_active', models.BooleanField()),
                ('patient', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='activation_records', to=settings.AUTH_USER_MODEL)),
                ('requested_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='requested_activation_records', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddField(
            model_name='patientprofile',
            name='is_account_active',
            field=models.BooleanField(default=True),
        ),
    ]
