# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-06-28 00:50
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0008_auto_20160626_2107'),
    ]

    operations = [
        migrations.CreateModel(
            name='DeactivationReason',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reason', models.CharField(max_length=255, unique=True)),
            ],
        ),
        migrations.RemoveField(
            model_name='activationrecord',
            name='reason',
        ),
        migrations.AddField(
            model_name='activationrecord',
            name='notification_method',
            field=models.TextField(default=''),
            preserve_default=False,
        ),
    ]
