# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-06-28 00:50
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0009_auto_20160627_1950'),
    ]

    operations = [
        migrations.AddField(
            model_name='activationrecord',
            name='reason',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='+', to='accounts.DeactivationReason'),
        ),
    ]
