# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-06-30 18:24
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0010_activationrecord_reason'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='activationrecord',
            name='is_active',
        ),
        migrations.RemoveField(
            model_name='patientprofile',
            name='is_account_active',
        ),
        migrations.AddField(
            model_name='activationrecord',
            name='new_status',
            field=models.CharField(choices=[(b'active', b'Active'), (b'termed', b'Termed'), (b'suspended', b'Suspended')], default='active', max_length=255),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='patientprofile',
            name='account_status',
            field=models.CharField(choices=[(b'active', b'Active'), (b'termed', b'Termed'), (b'suspended', b'Suspended')], default=b'active', editable=False, max_length=255),
        ),
    ]
