# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-07-31 00:24
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0015_auto_20160730_1933'),
    ]

    database_operations = [
        migrations.AlterModelTable(
            'DeactivationReason', 'dropdowns_deactivationreason')
    ]

    state_operations = [
        migrations.DeleteModel('DeactivationReason')
    ]

    operations = [
        migrations.SeparateDatabaseAndState(
            database_operations=database_operations,
            state_operations=state_operations)
    ]
