# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-07-31 13:24
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0016_auto_20160730_1933'),
        ('dropdowns', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='activationrecord',
            name='reason',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='+', to='dropdowns.DeactivationReason'),
        ),
    ]
