# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-07-31 14:46
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('dropdowns', '0004_auto_20160731_0946'),
        ('accounts', '0018_patientcommunication_patientcommunicationnote'),
    ]

    operations = [
        migrations.AddField(
            model_name='patientcommunication',
            name='description',
            field=models.TextField(default=''),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='patientcommunication',
            name='subcategory',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='communications', to='dropdowns.CommunicationSubcategory'),
            preserve_default=False,
        ),
    ]
