# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-07-31 15:31
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0019_auto_20160731_0946'),
    ]

    operations = [
        migrations.AddField(
            model_name='patientcommunication',
            name='datetime_updated',
            field=models.DateTimeField(default=datetime.datetime(2016, 7, 31, 15, 31, 23, 665724, tzinfo=utc)),
            preserve_default=False,
        ),
    ]
