# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-07-31 16:54
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('accounts', '0020_patientcommunication_datetime_updated'),
    ]

    operations = [
        migrations.AddField(
            model_name='patientcommunication',
            name='last_updated_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='+', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='patientcommunicationnote',
            name='communication',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='notes', to='accounts.PatientCommunication'),
        ),
    ]
