# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-08-03 02:14
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0024_patientcommunication_is_closed'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='patientcommunicationnote',
            name='replacements',
        ),
    ]
