# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-08-05 00:55
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0001_initial'),
        ('accounts', '0025_remove_patientcommunicationnote_replacements'),
    ]

    operations = [
        migrations.AddField(
            model_name='patientcommunicationnote',
            name='replacements',
            field=models.ManyToManyField(related_name='_patientcommunicationnote_replacements_+', to='products.ProductType'),
        ),
    ]
