# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-08-10 02:00
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0026_patientcommunicationnote_replacements'),
    ]

    operations = [
        migrations.AddField(
            model_name='patientcommunicationnote',
            name='quality_improvement_category',
            field=models.CharField(choices=[(b'complaint', b'Complaint'), (b'feedback', b'Feedback')], default='', max_length=255),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='patientcommunicationnote',
            name='content',
            field=models.TextField(verbose_name=b'Agent notes'),
        ),
    ]
