# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-08-10 02:05
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0027_auto_20160809_2100'),
    ]

    operations = [
        migrations.AddField(
            model_name='patientcommunicationnote',
            name='has_replacements',
            field=models.BooleanField(default=False, verbose_name=b'Replace Genesis products'),
        ),
        migrations.AddField(
            model_name='patientcommunicationnote',
            name='is_rma',
            field=models.BooleanField(default=False, verbose_name=b'Request Warranty Authorization (RA)'),
        ),
    ]
