# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-08-12 23:38
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0028_auto_20160809_2105'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='patientcommunication',
            name='is_closed',
        ),
    ]
