# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2017-04-05 17:21
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('dropdowns', '0011_communicationresolution'),
        ('accounts', '0030_auto_20160826_1548'),
    ]

    operations = [
        migrations.AddField(
            model_name='patientcommunication',
            name='resolution',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='+', to='dropdowns.CommunicationResolution'),
        ),
        migrations.AddField(
            model_name='patientcommunicationnote',
            name='resolution',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='+', to='dropdowns.CommunicationResolution'),
        ),
    ]
