# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2017-04-05 18:13
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0031_auto_20170405_1221'),
    ]

    operations = [
        migrations.AddField(
            model_name='patientcommunication',
            name='datetime_closed',
            field=models.DateTimeField(null=True),
        ),
    ]
