# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2017-05-31 17:26
from __future__ import unicode_literals

from django.db import migrations


def add_datetime_closed(apps, schema_editor):
    PatientCommunication = apps.get_model(
        'accounts', 'PatientCommunication')
    for communication in PatientCommunication.objects.filter(
            datetime_closed__isnull=True,
            status__is_closed=True):
        closed_notes = communication.notes.filter(
            change_status_to__is_closed=True)
        if closed_notes.count() > 0:
            communication.datetime_closed = closed_notes[0].datetime_added
            communication.save()


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0032_patientcommunication_datetime_closed'),
    ]

    operations = [
        migrations.RunPython(add_datetime_closed)
    ]
