# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2017-06-13 18:10
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0033_auto_20170531_1226'),
    ]

    operations = [
        migrations.AddField(
            model_name='genesisgroup',
            name='is_demo_group',
            field=models.BooleanField(default=False),
        ),
    ]
