# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2017-09-18 21:22
from __future__ import unicode_literals

from django.db import migrations


def add_base_permissions(apps, schema_editor):
    AdminPermission = apps.get_model("accounts", "AdminPermission")
    names = [
        'monitoring', 'manage-users', 'manage-devices',
        'manage-business-partners', 'manage-orders', 'contact-history',
        'cellular-management', 'system-auditing']
    for name in names:
        AdminPermission.objects.create(name=name)


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0036_auto_20170918_1601'),
    ]

    operations = [
        migrations.RunPython(add_base_permissions)
    ]
