# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2017-09-18 21:26
from __future__ import unicode_literals

from django.db import migrations


def make_admin_profiles(apps, schema_editor):
    AdminProfile = apps.get_model("accounts", "AdminProfile")
    User = apps.get_model("auth", "User")
    for user in User.objects.filter(is_staff=True):
        AdminProfile.objects.create(user=user, is_super_user=user.is_superuser)


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0037_auto_20170918_1622'),
    ]

    operations = [
        migrations.RunPython(make_admin_profiles)
    ]
