# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2017-09-19 02:37
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0039_auto_20170918_2011'),
    ]

    operations = [
        migrations.AddField(
            model_name='patientprofile',
            name='account_termination_date',
            field=models.DateTimeField(null=True),
        ),
    ]
