# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2017-09-25 21:22
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0040_patientprofile_account_termination_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='genesisgroup',
            name='skip_device_deactivation',
            field=models.BooleanField(default=False),
        ),
    ]
