# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2017-10-10 18:14
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0042_auto_20170925_1938'),
    ]

    operations = [
        migrations.AlterField(
            model_name='company',
            name='billing_method',
            field=models.CharField(blank=True, choices=[(b'medical', b'Medical'), (b'pharmacy', b'Pharmacy')], max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='company',
            name='bin_id',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='company',
            name='group_identifier',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='company',
            name='minimum_refill_quantity',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='company',
            name='pcn_id',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='company',
            name='refill_method',
            field=models.CharField(blank=True, choices=[(b'subscription', b'Subscription'), (b'utilization', b'Utilization'), (b'employee_family', b'GHT Employee Family'), (b'demo', b'None / Demo')], max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='company',
            name='start_kit_size',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
