# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2017-10-16 23:12
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0043_auto_20171010_1314'),
    ]

    operations = [
        migrations.AddField(
            model_name='company',
            name='glucose_control_refill_frequency',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='company',
            name='lancing_refill_frequency',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='company',
            name='bin_id',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name=b'BIN'),
        ),
        migrations.AlterField(
            model_name='company',
            name='pcn_id',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name=b'PCN'),
        ),
    ]
