# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-10-24 03:33
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0044_auto_20171016_1812'),
    ]

    operations = [
        migrations.AddField(
            model_name='patientprofile',
            name='bin_number',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name=b'BIN'),
        ),
        migrations.AddField(
            model_name='patientprofile',
            name='pcn_number',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name=b'PCN'),
        ),
    ]
