# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-10-24 15:28
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0045_auto_20171023_2233'),
    ]

    operations = [
        migrations.AddField(
            model_name='patientprofile',
            name='billing_method',
            field=models.CharField(blank=True, choices=[(b'medical', b'Medical'), (b'pharmacy', b'Pharmacy')], max_length=255, null=True),
        ),
    ]
