# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-10-31 06:00
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0046_patientprofile_billing_method'),
    ]

    operations = [
        migrations.AddField(
            model_name='patientprofile',
            name='glucose_control_refill_frequency',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='patientprofile',
            name='lancing_refill_frequency',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='patientprofile',
            name='refill_method',
            field=models.CharField(blank=True, choices=[(b'subscription', b'Subscription'), (b'utilization', b'Utilization'), (b'employee_family', b'GHT Employee Family'), (b'demo', b'None / Demo')], max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='company',
            name='glucose_control_refill_frequency',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='company',
            name='lancing_refill_frequency',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
    ]
