# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-10-31 07:28
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0047_auto_20171031_0100'),
    ]

    operations = [
        migrations.AddField(
            model_name='company',
            name='glucose_strip_refill_frequency',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='patientprofile',
            name='glucose_strip_refill_frequency',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='patientprofile',
            name='last_refill_datetime',
            field=models.DateTimeField(null=True),
        ),
    ]
