# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-10-31 18:33
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('pharmacy', '0001_initial'),
        ('accounts', '0048_auto_20171031_0228'),
    ]

    operations = [
        migrations.AddField(
            model_name='patientprofile',
            name='rx_partner',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='patients', to='pharmacy.PharmacyPartner'),
        ),
    ]
