# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-11-24 22:40
from __future__ import unicode_literals

from django.db import migrations


def populate_bin_pcn(apps, schema_editor):
    PatientProfile = apps.get_model('accounts', 'PatientProfile')
    for profile in PatientProfile.objects.filter(company__isnull=False):
        changed = False
        if not profile.bin_number:
            profile.bin_number = profile.company.bin_id
            changed = True
        if not profile.pcn_number:
            profile.pcn_number = profile.company.pcn_id
            changed = True
        if changed:
            profile.save()


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0050_remove_patientprofile_last_refill_datetime'),
    ]

    operations = [
        migrations.RunPython(populate_bin_pcn)
    ]
