# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-12-22 17:15
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0051_auto_20171124_1640'),
    ]

    operations = [
        migrations.AlterField(
            model_name='patientprofile',
            name='api_username',
            field=models.CharField(blank=True, max_length=255, null=True, unique=True),
        ),
    ]
