# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2018-03-07 04:24
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('pharmacy', '0002_auto_20171120_1816'),
        ('accounts', '0052_auto_20171222_1115'),
    ]

    operations = [
        migrations.AddField(
            model_name='company',
            name='default_pharmacy',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='companies', to='pharmacy.PharmacyPartner'),
        ),
    ]
