# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2018-03-07 14:13
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0053_company_default_pharmacy'),
    ]

    operations = [
        migrations.AddField(
            model_name='patientprofile',
            name='rh_member_id',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
