# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2018-03-14 13:27
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0054_patientprofile_rh_member_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='patientprofile',
            name='preferred_contact_method',
            field=models.CharField(choices=[(b'email', b'Email'), (b'phone', b'Phone')], default=b'phone', max_length=255),
        ),
    ]
