# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2018-03-14 13:51
from __future__ import unicode_literals

from django.db import migrations


def update_patient_statuses(apps, schema_editor):
    PatientProfile = apps.get_model("accounts", "PatientProfile")
    for profile in PatientProfile.objects.filter(
            account_status__isnull=True):
        profile.account_status = PatientProfile.ACCOUNT_STATUS_ACTIVE
        profile.save()


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0056_auto_20180314_0827'),
    ]

    operations = [
        migrations.RunPython(update_patient_statuses)
    ]
