# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2018-06-07 18:15
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0057_auto_20180314_0851'),
    ]

    operations = [
        migrations.AlterField(
            model_name='company',
            name='default_pharmacy',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='companies', to='pharmacy.PharmacyPartner'),
        ),
    ]
