# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2018-07-28 04:17
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0058_auto_20180607_1315'),
    ]

    operations = [
        migrations.AddField(
            model_name='genesisgroup',
            name='is_no_pii',
            field=models.BooleanField(default=False),
        ),
    ]
