# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2018-07-28 04:44
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0059_genesisgroup_is_no_pii'),
    ]

    operations = [
        migrations.AlterField(
            model_name='genesisgroup',
            name='group_type',
            field=models.CharField(choices=[(b'healthcare_provider', b'Healthcare Provider'), (b'insurance_administrator', b'Insurance Administrator'), (b'disease_management_organization', b'Disease Management Organization'), (b'pharmacist', b'Pharmacist'), (b'pii_restricted', b'PII Restricted')], max_length=255),
        ),
    ]
