# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2018-07-28 23:55
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0006_auto_20160522_1527'),
        ('accounts', '0062_auto_20180728_1804'),
    ]

    operations = [
        migrations.AddField(
            model_name='company',
            name='api_partner',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='companies', to='api.APIPartner'),
        ),
    ]
