# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2018-07-29 00:19
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('nursing', '0001_initial'),
        ('accounts', '0063_company_api_partner'),
    ]

    operations = [
        migrations.AddField(
            model_name='company',
            name='nursing_group',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='nursing_groups', to='nursing.NursingGroup'),
        ),
    ]
