# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2018-08-24 10:14
from __future__ import unicode_literals

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0064_company_nursing_group'),
    ]

    operations = [
        migrations.AlterField(
            model_name='patientcommunication',
            name='datetime_added',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
