# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2018-09-17 09:47
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0065_auto_20180824_0514'),
    ]

    operations = [
        migrations.AddField(
            model_name='genesisgroup',
            name='should_generate_refill_files',
            field=models.BooleanField(default=False),
        ),
    ]
