# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2019-01-06 21:31
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0067_auto_20190113_1746'),
    ]

    operations = [
        migrations.AddField(
            model_name='patientprofile',
            name='account_activation_datetime',
            field=models.DateTimeField(null=True),
        ),
    ]
