# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2019-01-30 13:09
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0068_patientprofile_account_activation_datetime'),
    ]

    operations = [
        migrations.AddField(
            model_name='genesisgroup',
            name='exclude_from_orders',
            field=models.BooleanField(default=False),
        ),
    ]
