# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2019-03-29 18:40
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0069_genesisgroup_exclude_from_orders'),
    ]

    operations = [
        migrations.AddField(
            model_name='patientprofile',
            name='welcome_text_sent',
            field=models.BooleanField(default=False),
        ),
    ]
