# Generated by Django 3.0.5 on 2020-06-01 04:44

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('dropdowns', '0016_communicationcategory_is_active'),
        ('pharmacy', '0003_auto_20180728_0741'),
        ('nursing', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('readings', '0005_auto_20200601_0444'),
        ('api', '0008_auto_20200601_0444'),
        ('accounts', '0070_patientprofile_welcome_text_sent'),
    ]

    operations = [
        migrations.AlterField(
            model_name='activationrecord',
            name='new_status',
            field=models.CharField(choices=[('active', 'Active'), ('termed', 'Termed'), ('suspended', 'Suspended')], max_length=255),
        ),
        migrations.AlterField(
            model_name='activationrecord',
            name='patient',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='activation_records', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='activationrecord',
            name='reason',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='dropdowns.DeactivationReason'),
        ),
        migrations.AlterField(
            model_name='activationrecord',
            name='requested_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='requested_activation_records', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='adminprofile',
            name='user',
            field=models.OneToOneField(limit_choices_to={'patient_profile__isnull': True, 'professional_profile__isnull': True}, on_delete=django.db.models.deletion.CASCADE, related_name='admin_profile', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='company',
            name='api_partner',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='companies', to='api.APIPartner'),
        ),
        migrations.AlterField(
            model_name='company',
            name='billing_method',
            field=models.CharField(blank=True, choices=[('medical', 'Medical'), ('pharmacy', 'Pharmacy')], max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='company',
            name='bin_id',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='BIN'),
        ),
        migrations.AlterField(
            model_name='company',
            name='default_pharmacy',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='companies', to='pharmacy.PharmacyPartner'),
        ),
        migrations.AlterField(
            model_name='company',
            name='group',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='companies', to='accounts.GenesisGroup'),
        ),
        migrations.AlterField(
            model_name='company',
            name='nursing_group',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='nursing_groups', to='nursing.NursingGroup'),
        ),
        migrations.AlterField(
            model_name='company',
            name='payor',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='companies', to='accounts.Payor'),
        ),
        migrations.AlterField(
            model_name='company',
            name='pcn_id',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='PCN'),
        ),
        migrations.AlterField(
            model_name='company',
            name='refill_method',
            field=models.CharField(blank=True, choices=[('subscription', 'Subscription'), ('utilization', 'Utilization'), ('employee_family', 'GHT Employee Family'), ('demo', 'None / Demo')], max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='demopatientprofile',
            name='glucose_reading_interval',
            field=models.CharField(choices=[('weekly', 'Weekly'), ('once_daily', 'Once a day'), ('three_times_daily', 'Three times a day'), ('five_times_daily', 'Five times a day')], default='five_times_daily', max_length=100),
        ),
        migrations.AlterField(
            model_name='demopatientprofile',
            name='user',
            field=models.OneToOneField(limit_choices_to={'patient_profile__isnull': False}, on_delete=django.db.models.deletion.CASCADE, related_name='demo_profile', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='demoscheduledreading',
            name='patient',
            field=models.ForeignKey(limit_choices_to={'patient_profile__demo_patient': True, 'patient_profile__isnull': False}, on_delete=django.db.models.deletion.CASCADE, related_name='scheduled_demo_readings', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='genesisgroup',
            name='group_type',
            field=models.CharField(choices=[('healthcare_provider', 'Healthcare Provider'), ('insurance_administrator', 'Insurance Administrator'), ('disease_management_organization', 'Disease Management Organization'), ('pharmacist', 'Pharmacist'), ('pii_restricted', 'PII Restricted')], max_length=255),
        ),
        migrations.AlterField(
            model_name='note',
            name='author',
            field=models.ForeignKey(limit_choices_to={'professional_profile__isnull': False}, on_delete=django.db.models.deletion.CASCADE, related_name='notes_authored', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='note',
            name='patient',
            field=models.ForeignKey(limit_choices_to={'patient_profile__isnull': False}, on_delete=django.db.models.deletion.CASCADE, related_name='notes_about', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='patientcommunication',
            name='added_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='communications_added', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='patientcommunication',
            name='category',
            field=models.ForeignKey(limit_choices_to={'is_active': True}, on_delete=django.db.models.deletion.CASCADE, related_name='communications', to='dropdowns.CommunicationCategory'),
        ),
        migrations.AlterField(
            model_name='patientcommunication',
            name='last_updated_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='patientcommunication',
            name='patient',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='communications', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='patientcommunication',
            name='resolution',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='dropdowns.CommunicationResolution'),
        ),
        migrations.AlterField(
            model_name='patientcommunication',
            name='status',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='dropdowns.CommunicationStatus'),
        ),
        migrations.AlterField(
            model_name='patientcommunication',
            name='subject',
            field=models.CharField(choices=[('inbound_epc', 'Inbound call EPC'), ('inbound_other', 'Inbound call other'), ('inbound_email', 'Inbound email'), ('outbound', 'Outbound call')], max_length=255),
        ),
        migrations.AlterField(
            model_name='patientcommunicationnote',
            name='added_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='communication_notes', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='patientcommunicationnote',
            name='communication',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='notes', to='accounts.PatientCommunication'),
        ),
        migrations.AlterField(
            model_name='patientcommunicationnote',
            name='content',
            field=models.TextField(verbose_name='Agent notes'),
        ),
        migrations.AlterField(
            model_name='patientcommunicationnote',
            name='has_replacements',
            field=models.BooleanField(default=False, verbose_name='Replace Genesis products'),
        ),
        migrations.AlterField(
            model_name='patientcommunicationnote',
            name='is_rma',
            field=models.BooleanField(default=False, verbose_name='Request Warranty Authorization (RA)'),
        ),
        migrations.AlterField(
            model_name='patientcommunicationnote',
            name='quality_improvement_category',
            field=models.CharField(choices=[('complaint', 'Complaint'), ('feedback', 'Feedback')], max_length=255),
        ),
        migrations.AlterField(
            model_name='patientcommunicationnote',
            name='resolution',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='dropdowns.CommunicationResolution'),
        ),
        migrations.AlterField(
            model_name='patientprofile',
            name='account_status',
            field=models.CharField(choices=[('active', 'Active'), ('termed', 'Termed'), ('suspended', 'Suspended')], default='active', editable=False, max_length=255),
        ),
        migrations.AlterField(
            model_name='patientprofile',
            name='billing_method',
            field=models.CharField(blank=True, choices=[('medical', 'Medical'), ('pharmacy', 'Pharmacy')], max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='patientprofile',
            name='bin_number',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='BIN'),
        ),
        migrations.AlterField(
            model_name='patientprofile',
            name='company',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='patients', to='accounts.Company'),
        ),
        migrations.AlterField(
            model_name='patientprofile',
            name='created_by_group',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_patients', to='accounts.GenesisGroup'),
        ),
        migrations.AlterField(
            model_name='patientprofile',
            name='gender',
            field=models.CharField(choices=[('male', 'Male'), ('female', 'Female')], max_length=10),
        ),
        migrations.AlterField(
            model_name='patientprofile',
            name='group',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='patients', to='accounts.GenesisGroup'),
        ),
        migrations.AlterField(
            model_name='patientprofile',
            name='last_reading',
            field=models.ForeignKey(editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='readings.GlucoseReading'),
        ),
        migrations.AlterField(
            model_name='patientprofile',
            name='nursing_group',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='patients', to='nursing.NursingGroup'),
        ),
        migrations.AlterField(
            model_name='patientprofile',
            name='pcn_number',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='PCN'),
        ),
        migrations.AlterField(
            model_name='patientprofile',
            name='preferred_contact_method',
            field=models.CharField(choices=[('email', 'Email'), ('phone', 'Phone')], default='phone', max_length=255),
        ),
        migrations.AlterField(
            model_name='patientprofile',
            name='refill_method',
            field=models.CharField(blank=True, choices=[('subscription', 'Subscription'), ('utilization', 'Utilization'), ('employee_family', 'GHT Employee Family'), ('demo', 'None / Demo')], max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='patientprofile',
            name='rx_partner',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='patients', to='pharmacy.PharmacyPartner'),
        ),
        migrations.AlterField(
            model_name='patientprofile',
            name='security_question1',
            field=models.CharField(blank=True, choices=[('grade_school', 'What Grade School did you attend?'), ('mother_maiden', "What is your mother's Maiden name?"), ('grandmother_madien', "What is your paternal grandmother's maiden name?"), ('street', 'What Street did you grow up on?'), ('eldest_sibling', 'In what year was your eldest sibling born?'), ('hs_mascot', 'What was the name of your high school mascot?'), ('favorite_pet', 'What is the name of your favorite pet?'), ('favorite_food', 'What is your favorite food?'), ('city_born', 'In what city where you born?')], max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='patientprofile',
            name='security_question2',
            field=models.CharField(blank=True, choices=[('grade_school', 'What Grade School did you attend?'), ('mother_maiden', "What is your mother's Maiden name?"), ('grandmother_madien', "What is your paternal grandmother's maiden name?"), ('street', 'What Street did you grow up on?'), ('eldest_sibling', 'In what year was your eldest sibling born?'), ('hs_mascot', 'What was the name of your high school mascot?'), ('favorite_pet', 'What is the name of your favorite pet?'), ('favorite_food', 'What is your favorite food?'), ('city_born', 'In what city where you born?')], max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='patientprofile',
            name='security_question3',
            field=models.CharField(blank=True, choices=[('grade_school', 'What Grade School did you attend?'), ('mother_maiden', "What is your mother's Maiden name?"), ('grandmother_madien', "What is your paternal grandmother's maiden name?"), ('street', 'What Street did you grow up on?'), ('eldest_sibling', 'In what year was your eldest sibling born?'), ('hs_mascot', 'What was the name of your high school mascot?'), ('favorite_pet', 'What is the name of your favorite pet?'), ('favorite_food', 'What is your favorite food?'), ('city_born', 'In what city where you born?')], max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='patientprofile',
            name='timezone_name',
            field=models.CharField(choices=[('US/Alaska', 'US/Alaska'), ('US/Aleutian', 'US/Aleutian'), ('US/Arizona', 'US/Arizona'), ('US/Central', 'US/Central'), ('US/East-Indiana', 'US/East-Indiana'), ('US/Eastern', 'US/Eastern'), ('US/Hawaii', 'US/Hawaii'), ('US/Indiana-Starke', 'US/Indiana-Starke'), ('US/Michigan', 'US/Michigan'), ('US/Mountain', 'US/Mountain'), ('US/Pacific', 'US/Pacific'), ('US/Samoa', 'US/Samoa')], default='US/Central', max_length=255),
        ),
        migrations.AlterField(
            model_name='patientprofile',
            name='user',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='patient_profile', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='patientprofile',
            name='validation_status',
            field=models.CharField(choices=[('active', 'active'), ('pending', 'pending')], editable=False, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='professionalprofile',
            name='security_question1',
            field=models.CharField(blank=True, choices=[('grade_school', 'What Grade School did you attend?'), ('mother_maiden', "What is your mother's Maiden name?"), ('grandmother_madien', "What is your paternal grandmother's maiden name?"), ('street', 'What Street did you grow up on?'), ('eldest_sibling', 'In what year was your eldest sibling born?'), ('hs_mascot', 'What was the name of your high school mascot?'), ('favorite_pet', 'What is the name of your favorite pet?'), ('favorite_food', 'What is your favorite food?'), ('city_born', 'In what city where you born?')], max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='professionalprofile',
            name='security_question2',
            field=models.CharField(blank=True, choices=[('grade_school', 'What Grade School did you attend?'), ('mother_maiden', "What is your mother's Maiden name?"), ('grandmother_madien', "What is your paternal grandmother's maiden name?"), ('street', 'What Street did you grow up on?'), ('eldest_sibling', 'In what year was your eldest sibling born?'), ('hs_mascot', 'What was the name of your high school mascot?'), ('favorite_pet', 'What is the name of your favorite pet?'), ('favorite_food', 'What is your favorite food?'), ('city_born', 'In what city where you born?')], max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='professionalprofile',
            name='security_question3',
            field=models.CharField(blank=True, choices=[('grade_school', 'What Grade School did you attend?'), ('mother_maiden', "What is your mother's Maiden name?"), ('grandmother_madien', "What is your paternal grandmother's maiden name?"), ('street', 'What Street did you grow up on?'), ('eldest_sibling', 'In what year was your eldest sibling born?'), ('hs_mascot', 'What was the name of your high school mascot?'), ('favorite_pet', 'What is the name of your favorite pet?'), ('favorite_food', 'What is your favorite food?'), ('city_born', 'In what city where you born?')], max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='professionalprofile',
            name='timezone_name',
            field=models.CharField(choices=[('US/Alaska', 'US/Alaska'), ('US/Aleutian', 'US/Aleutian'), ('US/Arizona', 'US/Arizona'), ('US/Central', 'US/Central'), ('US/East-Indiana', 'US/East-Indiana'), ('US/Eastern', 'US/Eastern'), ('US/Hawaii', 'US/Hawaii'), ('US/Indiana-Starke', 'US/Indiana-Starke'), ('US/Michigan', 'US/Michigan'), ('US/Mountain', 'US/Mountain'), ('US/Pacific', 'US/Pacific'), ('US/Samoa', 'US/Samoa')], default='US/Central', max_length=255),
        ),
    ]
