# Generated by Django 3.0.8 on 2020-09-27 17:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('nursing', '0001_initial'),
        ('accounts', '0074_remove_patientprofile_doctors_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='company',
            name='not_enough_recent_readings_interval',
            field=models.PositiveIntegerField(null=True),
        ),
        migrations.AddField(
            model_name='company',
            name='not_enough_recent_readings_minimum',
            field=models.PositiveIntegerField(null=True),
        ),
        migrations.AddField(
            model_name='company',
            name='reading_too_high_interval',
            field=models.PositiveIntegerField(null=True),
        ),
        migrations.AddField(
            model_name='company',
            name='reading_too_high_limit',
            field=models.PositiveIntegerField(null=True),
        ),
        migrations.AddField(
            model_name='company',
            name='reading_too_high_threshold',
            field=models.PositiveIntegerField(null=True),
        ),
        migrations.AddField(
            model_name='company',
            name='reading_too_low_interval',
            field=models.PositiveIntegerField(null=True),
        ),
        migrations.AddField(
            model_name='company',
            name='reading_too_low_limit',
            field=models.PositiveIntegerField(null=True),
        ),
        migrations.AddField(
            model_name='company',
            name='reading_too_low_threshold',
            field=models.PositiveIntegerField(null=True),
        ),
        migrations.AddField(
            model_name='genesisgroup',
            name='not_enough_recent_readings_interval',
            field=models.PositiveIntegerField(null=True),
        ),
        migrations.AddField(
            model_name='genesisgroup',
            name='not_enough_recent_readings_minimum',
            field=models.PositiveIntegerField(null=True),
        ),
        migrations.AddField(
            model_name='genesisgroup',
            name='nursing_group',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='genesis_groups', to='nursing.NursingGroup'),
        ),
        migrations.AddField(
            model_name='genesisgroup',
            name='reading_too_high_interval',
            field=models.PositiveIntegerField(null=True),
        ),
        migrations.AddField(
            model_name='genesisgroup',
            name='reading_too_high_limit',
            field=models.PositiveIntegerField(null=True),
        ),
        migrations.AddField(
            model_name='genesisgroup',
            name='reading_too_high_threshold',
            field=models.PositiveIntegerField(null=True),
        ),
        migrations.AddField(
            model_name='genesisgroup',
            name='reading_too_low_interval',
            field=models.PositiveIntegerField(null=True),
        ),
        migrations.AddField(
            model_name='genesisgroup',
            name='reading_too_low_limit',
            field=models.PositiveIntegerField(null=True),
        ),
        migrations.AddField(
            model_name='genesisgroup',
            name='reading_too_low_threshold',
            field=models.PositiveIntegerField(null=True),
        ),
        migrations.AddField(
            model_name='patientprofile',
            name='not_enough_recent_readings_interval',
            field=models.PositiveIntegerField(null=True),
        ),
        migrations.AddField(
            model_name='patientprofile',
            name='not_enough_recent_readings_minimum',
            field=models.PositiveIntegerField(null=True),
        ),
        migrations.AddField(
            model_name='patientprofile',
            name='reading_too_high_interval',
            field=models.PositiveIntegerField(null=True),
        ),
        migrations.AddField(
            model_name='patientprofile',
            name='reading_too_high_limit',
            field=models.PositiveIntegerField(null=True),
        ),
        migrations.AddField(
            model_name='patientprofile',
            name='reading_too_high_threshold',
            field=models.PositiveIntegerField(null=True),
        ),
        migrations.AddField(
            model_name='patientprofile',
            name='reading_too_low_interval',
            field=models.PositiveIntegerField(null=True),
        ),
        migrations.AddField(
            model_name='patientprofile',
            name='reading_too_low_limit',
            field=models.PositiveIntegerField(null=True),
        ),
        migrations.AddField(
            model_name='patientprofile',
            name='reading_too_low_threshold',
            field=models.PositiveIntegerField(null=True),
        ),
        migrations.AddField(
            model_name='professionalprofile',
            name='nursing_group',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='professionals', to='nursing.NursingGroup'),
        ),
    ]
