# Generated by Django 3.0.8 on 2020-12-06 22:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('nursing', '0001_initial'),
        ('accounts', '0076_auto_20200927_1533'),
    ]

    operations = [
        migrations.AddField(
            model_name='company',
            name='compliance_nursing_group',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='compliance_groups', to='nursing.NursingGroup'),
        ),
        migrations.AlterField(
            model_name='company',
            name='nursing_group',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='groups', to='nursing.NursingGroup'),
        ),
    ]
