# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-04-24 21:34
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('readings', '0001_initial'),
        ('gdrives', '0002_auto_20160225_1401'),
    ]

    operations = [
        migrations.AddField(
            model_name='gdrive',
            name='last_reading',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='readings.GlucoseReading'),
        ),
    ]
