# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-07-01 12:40
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('gdrives', '0003_gdrive_last_reading'),
    ]

    operations = [
        migrations.AlterField(
            model_name='gdrive',
            name='group',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='gdrives', to='accounts.GenesisGroup'),
        ),
        migrations.AlterField(
            model_name='gdrive',
            name='last_assigned_patient',
            field=models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='gdrive',
            name='partner',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='gdrives', to='api.APIPartner'),
        ),
        migrations.AlterField(
            model_name='gdrive',
            name='patient',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='gdrives', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='gdrive',
            name='professional',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='child_gdrives', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='gdrive',
            name='verizon_patient',
            field=models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='verizon_devices', to=settings.AUTH_USER_MODEL),
        ),
    ]
