# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-07-16 15:39
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('monitoring', '0009_auto_20160716_1038'),
        ('gdrives', '0005_auto_20160701_0748'),
    ]

    operations = [
        migrations.AddField(
            model_name='gdrivelogentry',
            name='reading_server',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='log_entries', to='monitoring.ReadingServer'),
        ),
    ]
