# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-07-30 13:20
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gdrives', '0007_auto_20160728_2108'),
    ]

    operations = [
        migrations.AddField(
            model_name='gdrive',
            name='phone_number',
            field=models.CharField(default='', max_length=255),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='gdrive',
            name='status',
            field=models.CharField(blank=True, choices=[(b'new', b'New'), (b'active', b'Active'), (b'inactive', b'Inactive'), (b'suspended', b'Suspended')], default=b'new', editable=False, max_length=255),
        ),
    ]
