# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-07-31 02:06
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('dropdowns', '0002_auto_20160730_2105'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('gdrives', '0008_auto_20160730_0820'),
    ]

    operations = [
        migrations.CreateModel(
            name='GDriveComplaint',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.TextField()),
                ('datetime_added', models.DateTimeField(auto_now_add=True)),
                ('datetime_modified', models.DateTimeField(auto_now=True)),
                ('is_resolved', models.BooleanField(default=False)),
                ('added_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='complaints_added', to=settings.AUTH_USER_MODEL)),
                ('device', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='complaints', to='gdrives.GDrive')),
                ('last_modified_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('problem', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='complaints', to='dropdowns.DeviceProblem')),
            ],
        ),
    ]
