# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-07-31 19:58
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('dropdowns', '0006_gdrivenonconformitytype'),
        ('gdrives', '0009_gdrivecomplaint'),
    ]

    operations = [
        migrations.CreateModel(
            name='GDriveNonConformity',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('datetime_added', models.DateTimeField(auto_now_add=True)),
                ('description', models.TextField()),
                ('tray_number', models.CharField(max_length=255)),
                ('added_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('non_conformity_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dropdowns.GDriveNonConformityType')),
            ],
        ),
    ]
