# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-07-31 20:03
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gdrives', '0011_auto_20160731_1503'),
    ]

    operations = [
        migrations.AddField(
            model_name='gdrivecomplaint',
            name='is_validated',
            field=models.BooleanField(default=False),
        ),
    ]
