# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-08-03 01:22
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gdrives', '0013_auto_20160731_1507'),
    ]

    operations = [
        migrations.CreateModel(
            name='GDriveCarton',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.CharField(max_length=255, unique=True)),
            ],
        ),
        migrations.RemoveField(
            model_name='gdrive',
            name='lot',
        ),
        migrations.AddField(
            model_name='gdrive',
            name='carton_number',
            field=models.CharField(default='', max_length=255),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='gdrive',
            name='datetime_replaced',
            field=models.DateTimeField(null=True),
        ),
        migrations.AddField(
            model_name='gdrive',
            name='lot_number',
            field=models.CharField(default='', max_length=255),
            preserve_default=False,
        ),
    ]
