# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-08-03 01:27
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('gdrives', '0014_auto_20160802_2022'),
    ]

    operations = [
        migrations.DeleteModel(
            name='GDriveCarton',
        ),
        migrations.DeleteModel(
            name='GDriveLot',
        ),
    ]
