# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-08-06 22:38
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('gdrives', '0015_auto_20160802_2027'),
    ]

    operations = [
        migrations.CreateModel(
            name='GDriveInspectionRecord',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('datetime_inspected', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.AddField(
            model_name='gdrive',
            name='network_status',
            field=models.CharField(choices=[(b'inactive', b'Inactive'), (b'active', b'Active'), (b'suspended', b'Suspended')], default=b'inactive', max_length=255),
        ),
        migrations.AlterField(
            model_name='gdrive',
            name='status',
            field=models.CharField(blank=True, choices=[(b'new', b'New'), (b'available', b'Available'), (b'assigned', b'Assigned'), (b'unassigned', b'Unassigned'), (b'repairable', b'Repairable'), (b'reworked', b'Reworked'), (b'returned', b'Returned'), (b'demo', b'Demo')], default=b'new', editable=False, max_length=255),
        ),
        migrations.AddField(
            model_name='gdriveinspectionrecord',
            name='device',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='inspection_records', to='gdrives.GDrive'),
        ),
        migrations.AddField(
            model_name='gdriveinspectionrecord',
            name='inspected_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='inspection_records', to=settings.AUTH_USER_MODEL),
        ),
    ]
