# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-08-07 00:07
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('gdrives', '0016_auto_20160806_1738'),
    ]

    operations = [
        migrations.CreateModel(
            name='GDriveModuleVersion',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, unique=True)),
            ],
        ),
        migrations.AddField(
            model_name='gdrive',
            name='module_version',
            field=models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='devices', to='gdrives.GDriveModuleVersion'),
        ),
    ]
