# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-08-07 18:57
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gdrives', '0020_auto_20160806_2325'),
    ]

    operations = [
        migrations.AlterField(
            model_name='gdrive',
            name='phone_number',
            field=models.CharField(blank=True, max_length=255),
        ),
    ]
