# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-08-08 17:06
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gdrives', '0021_auto_20160807_1357'),
    ]

    operations = [
        migrations.AddField(
            model_name='gdrive',
            name='datetime_reworked',
            field=models.DateTimeField(null=True),
        ),
    ]
