# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-08-08 23:19
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('gdrives', '0022_gdrive_datetime_reworked'),
    ]

    operations = [
        migrations.CreateModel(
            name='GDriveReworkRecord',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('datetime_reworked', models.DateTimeField(auto_now_add=True)),
                ('details', models.TextField()),
            ],
        ),
        migrations.AddField(
            model_name='gdrive',
            name='datetime_inspected',
            field=models.DateTimeField(null=True),
        ),
        migrations.AddField(
            model_name='gdrivereworkrecord',
            name='device',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='rework_records', to='gdrives.GDrive'),
        ),
        migrations.AddField(
            model_name='gdrivereworkrecord',
            name='reworked_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='rework_records', to=settings.AUTH_USER_MODEL),
        ),
    ]
