# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-08-09 00:48
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dropdowns', '0008_auto_20160802_2109'),
        ('gdrives', '0024_auto_20160808_1832'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='gdrivecomplaint',
            name='problem',
        ),
        migrations.AddField(
            model_name='gdrivecomplaint',
            name='problem',
            field=models.ManyToManyField(related_name='complaints', to='dropdowns.DeviceProblem'),
        ),
    ]
