# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-08-09 00:56
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('gdrives', '0025_auto_20160808_1948'),
    ]

    operations = [
        migrations.RenameField(
            model_name='gdrivecomplaint',
            old_name='problem',
            new_name='problems',
        ),
    ]
