# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-08-10 02:00
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gdrives', '0026_auto_20160808_1956'),
    ]

    operations = [
        migrations.AlterField(
            model_name='gdrive',
            name='carton_number',
            field=models.CharField(max_length=255, verbose_name=b'Warehouse carton number'),
        ),
        migrations.AlterField(
            model_name='gdrive',
            name='date_shipped',
            field=models.DateField(null=True, verbose_name=b'Manufacturer shipped date'),
        ),
        migrations.AlterField(
            model_name='gdrive',
            name='device_id',
            field=models.CharField(max_length=100, unique=True, verbose_name=b'Serial number'),
        ),
    ]
