# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-08-15 21:48
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('gdrives', '0029_auto_20160812_2021'),
    ]

    operations = [
        migrations.CreateModel(
            name='GDriveWarehouseCarton',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.CharField(max_length=255, unique=True)),
            ],
        ),
        migrations.RemoveField(
            model_name='gdrive',
            name='warehouse_number',
        ),
        migrations.AlterField(
            model_name='gdrivereworkrecord',
            name='details',
            field=models.TextField(verbose_name=b'Rework details'),
        ),
        migrations.AddField(
            model_name='gdrive',
            name='warehouse_carton',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='devices', to='gdrives.GDriveWarehouseCarton'),
        ),
    ]
