# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-08-16 01:56
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('gdrives', '0030_auto_20160815_1648'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='gdrive',
            name='carton',
        ),
        migrations.AddField(
            model_name='gdrive',
            name='manufacturer_carton',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='devices', to='gdrives.GDriveCarton', verbose_name=b'Mfg. carton'),
        ),
        migrations.AlterField(
            model_name='gdrive',
            name='warehouse_carton',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='devices', to='gdrives.GDriveWarehouseCarton', verbose_name=b'Warehouse carton'),
        ),
    ]
