# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-08-16 03:09
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('gdrives', '0031_auto_20160815_2056'),
    ]

    operations = [
        migrations.CreateModel(
            name='GDriveManufacturerCarton',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.CharField(max_length=255, unique=True)),
                ('lot_number', models.CharField(max_length=255)),
                ('date_shipped', models.DateField()),
                ('is_inspected', models.BooleanField(default=False)),
            ],
        ),
        migrations.RemoveField(
            model_name='gdrive',
            name='date_shipped',
        ),
        migrations.AlterField(
            model_name='gdrive',
            name='manufacturer_carton',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='devices', to='gdrives.GDriveManufacturerCarton', verbose_name=b'Mfg. carton'),
        ),
        migrations.DeleteModel(
            name='GDriveCarton',
        ),
    ]
