# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-08-16 15:46
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('gdrives', '0032_auto_20160815_2209'),
    ]

    operations = [
        migrations.AddField(
            model_name='gdrivemanufacturercarton',
            name='datetime_added',
            field=models.DateTimeField(auto_now_add=True, default=datetime.datetime(2016, 8, 16, 15, 46, 40, 37316, tzinfo=utc)),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='gdrivewarehousecarton',
            name='datetime_added',
            field=models.DateTimeField(auto_now_add=True, default=datetime.datetime(2016, 8, 16, 15, 46, 43, 637255, tzinfo=utc)),
            preserve_default=False,
        ),
    ]
