# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-08-17 03:43
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('gdrives', '0033_auto_20160816_1046'),
    ]

    operations = [
        migrations.AddField(
            model_name='gdrivemanufacturercarton',
            name='approved_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='manufacturer_cartons_approved', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='gdrivemanufacturercarton',
            name='approved_datetime',
            field=models.DateTimeField(null=True),
        ),
    ]
