# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-08-18 17:32
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('gdrives', '0035_auto_20160817_1319'),
    ]

    operations = [
        migrations.AddField(
            model_name='gdrive',
            name='datetime_failed_delivery',
            field=models.DateTimeField(null=True),
        ),
        migrations.AlterField(
            model_name='gdrive',
            name='status',
            field=models.CharField(blank=True, choices=[(b'new', b'New'), (b'available', b'Available'), (b'assigned', b'Assigned'), (b'unassigned', b'Unassigned'), (b'repairable', b'Repairable'), (b'reworked', b'Reworked'), (b'returned', b'Returned'), (b'demo', b'Demo'), (b'failed delivery', b'Failed Delivery')], default=b'new', editable=False, max_length=255),
        ),
        migrations.AlterField(
            model_name='gdrivemanufacturercarton',
            name='firmware_version',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='devices', to='gdrives.GDriveFirmwareVersion'),
        ),
        migrations.AlterField(
            model_name='gdrivemanufacturercarton',
            name='module_version',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='devices', to='gdrives.GDriveModuleVersion'),
        ),
    ]
