# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-08-23 19:42
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('gdrives', '0038_auto_20160818_1342'),
    ]

    operations = [
        migrations.AddField(
            model_name='gdrivecomplaint',
            name='rma_notes',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='gdrivecomplaint',
            name='validated_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='+', to=settings.AUTH_USER_MODEL),
        ),
    ]
