# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2017-04-04 00:47
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('dropdowns', '0010_meterdisposition'),
        ('gdrives', '0043_auto_20160831_1645'),
    ]

    operations = [
        migrations.AddField(
            model_name='gdrive',
            name='segregation_disposition',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='+', to='dropdowns.MeterDisposition'),
        ),
    ]
