# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2017-04-20 13:44
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('dropdowns', '0011_communicationresolution'),
        ('gdrives', '0046_gdrivereworkrecord_ready_for_inspection'),
    ]

    operations = [
        migrations.CreateModel(
            name='GDriveComplaintUpdate',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rma_return_date', models.DateField(null=True)),
                ('is_validated', models.BooleanField(default=False)),
                ('complaint', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='updates', to='gdrives.GDriveComplaint')),
                ('found_problems', models.ManyToManyField(related_name='_gdrivecomplaintupdate_found_problems_+', to='dropdowns.DeviceProblem')),
                ('reported_problems', models.ManyToManyField(related_name='update_complaints', to='dropdowns.DeviceProblem')),
            ],
        ),
    ]
