# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2017-04-20 13:45
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('gdrives', '0047_gdrivecomplaintupdate'),
    ]

    operations = [
        migrations.AddField(
            model_name='gdrivecomplaintupdate',
            name='datetime_added',
            field=models.DateTimeField(auto_now_add=True, default=datetime.datetime(2017, 4, 20, 13, 45, 42, 150068, tzinfo=utc)),
            preserve_default=False,
        ),
    ]
