# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2017-04-20 13:48
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('gdrives', '0048_gdrivecomplaintupdate_datetime_added'),
    ]

    operations = [
        migrations.AddField(
            model_name='gdrivecomplaintupdate',
            name='updated_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='gdrive_complaint_updates', to=settings.AUTH_USER_MODEL),
        ),
    ]
