# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2017-04-20 13:52
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gdrives', '0049_gdrivecomplaintupdate_updated_by'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='gdrivecomplaintupdate',
            name='reported_problems',
        ),
        migrations.AddField(
            model_name='gdrivecomplaintupdate',
            name='rma_notes',
            field=models.TextField(null=True),
        ),
    ]
