# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2017-06-22 00:48
from __future__ import unicode_literals

from django.db import migrations


def set_dispositions(apps, schema_editor):
    GDrive = apps.get_model('gdrives', 'GDrive')
    MeterDisposition = apps.get_model('dropdowns', 'MeterDisposition')
    rw_vendor = MeterDisposition.objects.get(name="Reworked by Vendor")
    seg_rw = MeterDisposition.objects.get(name="Segregate for Rework")
    for device in GDrive.objects.filter(non_conformities__isnull=False):
        if device.status == 'reworked':
            device.segregation_disposition = rw_vendor
        else:
            device.segregation_disposition = seg_rw
        device.save()


class Migration(migrations.Migration):

    dependencies = [
        ('gdrives', '0050_auto_20170420_0852'),
        ('dropdowns', '0012_auto_20170621_1942')
    ]

    operations = [
        migrations.RunPython(set_dispositions)
    ]
