# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2017-09-19 01:11
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gdrives', '0051_auto_20170621_1948'),
    ]

    operations = [
        migrations.AddField(
            model_name='gdrive',
            name='datetime_network_status_activated',
            field=models.DateTimeField(null=True),
        ),
        migrations.AddField(
            model_name='gdrive',
            name='datetime_network_status_changed',
            field=models.DateTimeField(null=True),
        ),
        migrations.AddField(
            model_name='gdrive',
            name='ip_address',
            field=models.CharField(blank=True, max_length=255),
        ),
    ]
