# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2017-10-16 18:37
from __future__ import unicode_literals

from django.db import migrations


def change_network_inactive_statuses(apps, schema_editor):
    GDrive = apps.get_model('gdrives', 'GDrive')
    for gdrive in GDrive.objects.filter(network_status='inactive'):
        gdrive.network_status = 'deactivated'
        gdrive.save()


class Migration(migrations.Migration):

    dependencies = [
        ('gdrives', '0052_auto_20170918_2011'),
    ]

    operations = [
        migrations.RunPython(change_network_inactive_statuses)
    ]
