# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2017-10-16 19:17
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gdrives', '0053_auto_20171016_1337'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='gdrive',
            name='verizon_status',
        ),
        migrations.AlterField(
            model_name='gdrive',
            name='network_status',
            field=models.CharField(choices=[(b'deactivated', b'Deactivated'), (b'loaded', b'Loaded'), (b'active', b'Active'), (b'suspended', b'Suspended')], default=b'deactivated', max_length=255),
        ),
    ]
