# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2018-12-16 23:54
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gdrives', '0054_auto_20171016_1417'),
    ]

    operations = [
        migrations.AddField(
            model_name='gdrivewarehousecarton',
            name='is_shipped',
            field=models.BooleanField(default=False),
        ),
    ]
