# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2018-12-16 23:56
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0041_auto_20181211_1204'),
        ('gdrives', '0055_gdrivewarehousecarton_is_shipped'),
    ]

    operations = [
        migrations.AddField(
            model_name='gdrivewarehousecarton',
            name='shipment',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='orders.OrderShipment'),
        ),
    ]
