# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2018-12-18 00:12
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('gdrives', '0056_gdrivewarehousecarton_shipment'),
    ]

    operations = [
        migrations.AlterField(
            model_name='gdrivewarehousecarton',
            name='shipment',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='warehouse_cartons', to='orders.OrderShipment'),
        ),
    ]
