# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2019-03-30 19:59
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0048_auto_20190227_0543'),
        ('gdrives', '0058_gdrivewarehousecarton_rx_partner'),
    ]

    operations = [
        migrations.AddField(
            model_name='gdrive',
            name='shipment',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='gdrives', to='orders.OrderShipment'),
        ),
    ]
