# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2019-03-30 20:31
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gdrives', '0059_gdrive_shipment'),
    ]

    operations = [
        migrations.AddField(
            model_name='gdrive',
            name='reminder_text_sent',
            field=models.BooleanField(default=False),
        ),
    ]
