# Generated by Django 3.0.5 on 2020-06-01 04:44

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('dropdowns', '0016_communicationcategory_is_active'),
        ('pharmacy', '0003_auto_20180728_0741'),
        ('accounts', '0071_auto_20200601_0444'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('monitoring', '0013_auto_20200601_0444'),
        ('readings', '0005_auto_20200601_0444'),
        ('orders', '0048_auto_20190227_0543'),
        ('gdrives', '0060_gdrive_reminder_text_sent'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bloodpressuredevice',
            name='group',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='blood_pressure_devices', to='accounts.GenesisGroup'),
        ),
        migrations.AlterField(
            model_name='bloodpressuredevice',
            name='patient',
            field=models.ForeignKey(limit_choices_to={'patient_profile__isnull': False}, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='blood_pressure_devices', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='gdrive',
            name='device_id',
            field=models.CharField(max_length=100, unique=True, verbose_name='Serial number'),
        ),
        migrations.AlterField(
            model_name='gdrive',
            name='device_type',
            field=models.CharField(blank=True, default='glucose', max_length=100),
        ),
        migrations.AlterField(
            model_name='gdrive',
            name='last_reading',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='readings.GlucoseReading'),
        ),
        migrations.AlterField(
            model_name='gdrive',
            name='manufacturer_carton',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='devices', to='gdrives.GDriveManufacturerCarton', verbose_name='Mfg. carton'),
        ),
        migrations.AlterField(
            model_name='gdrive',
            name='network_status',
            field=models.CharField(choices=[('deactivated', 'Deactivated'), ('loaded', 'Loaded'), ('active', 'Active'), ('suspended', 'Suspended')], default='deactivated', max_length=255),
        ),
        migrations.AlterField(
            model_name='gdrive',
            name='professional',
            field=models.ForeignKey(blank=True, limit_choices_to={'groups__name': 'Professional'}, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='child_gdrives', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='gdrive',
            name='rx_partner',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='devices', to='gdrives.PharmacyPartner'),
        ),
        migrations.AlterField(
            model_name='gdrive',
            name='segregation_disposition',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='dropdowns.MeterDisposition'),
        ),
        migrations.AlterField(
            model_name='gdrive',
            name='shipment',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='gdrives', to='orders.OrderShipment'),
        ),
        migrations.AlterField(
            model_name='gdrive',
            name='status',
            field=models.CharField(blank=True, choices=[('new', 'New'), ('available', 'Available'), ('assigned', 'Assigned'), ('unassigned', 'Unassigned'), ('repairable', 'Repairable'), ('reworked', 'Reworked'), ('returned', 'Returned'), ('demo', 'Demo'), ('failed delivery', 'Failed Delivery')], default='new', editable=False, max_length=255),
        ),
        migrations.AlterField(
            model_name='gdrive',
            name='warehouse_carton',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='devices', to='gdrives.GDriveWarehouseCarton', verbose_name='Warehouse carton'),
        ),
        migrations.AlterField(
            model_name='gdrivecomplaint',
            name='added_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='complaints_added', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='gdrivecomplaint',
            name='last_modified_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='gdrivecomplaint',
            name='validated_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='gdrivecomplaintupdate',
            name='updated_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='gdrive_complaint_updates', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='gdriveinspectionrecord',
            name='device',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='inspection_records', to='gdrives.GDrive'),
        ),
        migrations.AlterField(
            model_name='gdriveinspectionrecord',
            name='inspected_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='inspection_records', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='gdrivelogentry',
            name='device',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='gdrives.GDrive'),
        ),
        migrations.AlterField(
            model_name='gdrivelogentry',
            name='reading_server',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='log_entries', to='monitoring.ReadingServer'),
        ),
        migrations.AlterField(
            model_name='gdrivemanufacturercarton',
            name='approved_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='manufacturer_cartons_approved', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='gdrivemanufacturercarton',
            name='firmware_version',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='devices', to='gdrives.GDriveFirmwareVersion'),
        ),
        migrations.AlterField(
            model_name='gdrivemanufacturercarton',
            name='module_version',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='devices', to='gdrives.GDriveModuleVersion'),
        ),
        migrations.AlterField(
            model_name='gdrivenonconformity',
            name='added_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='gdrivereworkrecord',
            name='details',
            field=models.TextField(verbose_name='Rework details'),
        ),
        migrations.AlterField(
            model_name='gdrivereworkrecord',
            name='device',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='rework_records', to='gdrives.GDrive'),
        ),
        migrations.AlterField(
            model_name='gdrivereworkrecord',
            name='new_disposition',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='dropdowns.MeterDisposition'),
        ),
        migrations.AlterField(
            model_name='gdrivereworkrecord',
            name='reworked_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='rework_records', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='gdrivetransmissionlogentry',
            name='decrypted_content',
            field=models.TextField(default=''),
        ),
        migrations.AlterField(
            model_name='gdrivetransmissionlogentry',
            name='error',
            field=models.TextField(default=''),
        ),
        migrations.AlterField(
            model_name='gdrivetransmissionlogentry',
            name='resolution',
            field=models.CharField(choices=[('unknown_device', 'Unknown Device'), ('no_patient', 'No Patient Assigned to Device'), ('valid', 'Successfully Processed'), ('invalid', 'Invalid Reading'), ('duplicate', 'Duplicate Reading'), ('processing_failed', 'Processing Failed'), ('invalid_measure', 'Invalid Measurement Type'), ('unresolved', 'Unresolved')], default='unresolved', max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='gdrivewarehousecarton',
            name='rx_partner',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='warehouse_cartons', to='pharmacy.PharmacyPartner'),
        ),
        migrations.AlterField(
            model_name='gdrivewarehousecarton',
            name='shipment',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='warehouse_cartons', to='orders.OrderShipment'),
        ),
        migrations.AlterField(
            model_name='weightdevice',
            name='group',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='weight_devices', to='accounts.GenesisGroup'),
        ),
        migrations.AlterField(
            model_name='weightdevice',
            name='patient',
            field=models.ForeignKey(limit_choices_to={'patient_profile__isnull': False}, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='weight_devices', to=settings.AUTH_USER_MODEL),
        ),
    ]
