# Generated by Django 3.0.8 on 2020-09-27 17:47

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('nursing', '0001_initial'),
        ('accounts', '0075_auto_20200927_1246'),
    ]

    operations = [
        migrations.CreateModel(
            name='NursingQueueEntry',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('entry_type', models.CharField(choices=[('readings too low', 'Readings Too Low'), ('readings too high', 'Readings Too High'), ('not enough recent readings', 'Not Enough Recent Readings')], max_length=255)),
                ('datetime_added', models.DateTimeField(default=django.utils.timezone.now)),
                ('due_date', models.DateField()),
                ('is_completed', models.BooleanField(default=False)),
                ('completed_datetime', models.DateTimeField(null=True)),
                ('nursing_group', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='nursing_queue_entries', to='nursing.NursingGroup')),
                ('patient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='nursing_queue_entries', to='accounts.PatientProfile')),
            ],
        ),
    ]
