# Generated by Django 3.0.8 on 2020-12-06 22:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nursing_queue', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='nursingqueueentry',
            name='entry_type',
            field=models.CharField(choices=[('readings too low', 'Low Reading'), ('readings too high', 'High Reading'), ('not enough recent readings', 'No Reading')], max_length=255),
        ),
    ]
