# Generated by Django 3.0.8 on 2020-12-13 22:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('nursing_queue', '0002_auto_20201206_1628'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='nursingqueueentry',
            name='nursing_group',
        ),
    ]
