# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-08-09 00:11
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='producttype',
            name='is_device',
            field=models.BooleanField(default=False),
        ),
    ]
