# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-08-12 02:01
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0002_producttype_is_device'),
    ]

    operations = [
        migrations.AlterField(
            model_name='producttype',
            name='is_device',
            field=models.BooleanField(default=False, verbose_name=b'Glucose Device'),
        ),
    ]
