# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-10-29 23:13
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0003_auto_20160811_2101'),
    ]

    operations = [
        migrations.AddField(
            model_name='producttype',
            name='is_bulk',
            field=models.BooleanField(default=False, help_text=b'If yes, this field will show up only in bulk orders.'),
        ),
    ]
