# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2019-02-27 11:43
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0007_producttype_box_quantity'),
    ]

    operations = [
        migrations.AlterField(
            model_name='producttype',
            name='category',
            field=models.CharField(choices=[(b'strips', b'Reading Strips'), (b'gdrive', b'Glucose Device'), (b'lancet', b'Lancets'), (b'lancing device', b'Lancing Device'), (b'control solution', b'Control Solution'), (b'pamphlet', b'Pamphlet')], max_length=255, null=True, unique=True),
        ),
    ]
