# Generated by Django 3.0.5 on 2020-06-01 04:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0008_auto_20190227_0543'),
    ]

    operations = [
        migrations.AlterField(
            model_name='producttype',
            name='category',
            field=models.CharField(choices=[('strips', 'Reading Strips'), ('gdrive', 'Glucose Device'), ('lancet', 'Lancets'), ('lancing device', 'Lancing Device'), ('control solution', 'Control Solution'), ('pamphlet', 'Pamphlet')], max_length=255, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='producttype',
            name='is_bulk',
            field=models.BooleanField(default=False, help_text='If yes, this field will show up only in bulk orders.'),
        ),
        migrations.AlterField(
            model_name='producttype',
            name='is_device',
            field=models.BooleanField(default=False, verbose_name='Glucose Device'),
        ),
        migrations.AlterField(
            model_name='producttype',
            name='is_refill',
            field=models.BooleanField(default=False, verbose_name='Strip refill item'),
        ),
    ]
