# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2017-10-10 18:04
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('gdrives', '0052_auto_20170918_2011'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('products', '0003_auto_20160811_2101'),
    ]

    operations = [
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('datetime_added', models.DateTimeField(auto_now_add=True)),
                ('category', models.CharField(max_length=255)),
                ('adjudicated_date', models.DateField(null=True)),
                ('is_claim_approved', models.BooleanField()),
                ('exception', models.CharField(max_length=255)),
                ('order_status', models.CharField(max_length=255)),
                ('is_complete', models.BooleanField(default=False)),
                ('patient', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='orders', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='OrderEntry',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.PositiveIntegerField()),
                ('is_fulfilled', models.BooleanField(default=False)),
                ('invoice_number', models.CharField(max_length=255)),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='entries', to='orders.Order')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='order_entries', to='products.ProductType')),
            ],
        ),
        migrations.CreateModel(
            name='OrderShipment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('shipping_class', models.CharField(max_length=255)),
                ('shipping_piece', models.CharField(max_length=255)),
                ('package_length', models.FloatField()),
                ('package_height', models.FloatField()),
                ('package_width', models.FloatField()),
                ('packed_date', models.DateField(null=True)),
                ('shipped_date', models.DateField(null=True)),
                ('ship_vendor', models.CharField(max_length=255)),
                ('tracking_number', models.CharField(max_length=255)),
                ('address_validated', models.BooleanField(default=False)),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='shipments', to='orders.Order')),
                ('packed_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='order_shipments_packed', to=settings.AUTH_USER_MODEL)),
                ('pharmacy_partner', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='shipments', to='gdrives.PharmacyPartner')),
                ('shipped_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='orders_shipped', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='OrderShipmentEntry',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.PositiveIntegerField()),
                ('expiration', models.DateField(null=True)),
                ('inventory_identifier', models.CharField(max_length=255)),
                ('order_shipment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='entries', to='orders.OrderShipment')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='shipment_entries', to='products.ProductType')),
            ],
        ),
    ]
