# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2017-10-16 23:12
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='order_type',
            field=models.CharField(choices=[(b'patient', b'Patient'), (b'bulk', b'Bulk')], default='', max_length=255),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='order',
            name='category',
            field=models.CharField(choices=[(b'normal', b'Normal')], max_length=255),
        ),
    ]
