# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2017-10-17 13:25
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('orders', '0003_auto_20171016_1956'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='is_locked',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='order',
            name='locked_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='locked_orders', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='order',
            name='locked_datetime',
            field=models.DateTimeField(null=True),
        ),
        migrations.AlterField(
            model_name='order',
            name='order_status',
            field=models.CharField(choices=[(b'open', b'Open'), (b'completed', b'Completed'), (b'canceled', b'Canceled')], default=b'open', max_length=255),
        ),
    ]
