# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2017-10-17 13:37
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0004_auto_20171017_0825'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ordershipment',
            name='ship_vendor',
            field=models.CharField(choices=[(b'ups', b'UPS')], max_length=255),
        ),
        migrations.AlterField(
            model_name='ordershipment',
            name='shipping_class',
            field=models.CharField(choices=[(b'box', b'Box')], max_length=255),
        ),
        migrations.AlterField(
            model_name='ordershipment',
            name='shipping_piece',
            field=models.CharField(choices=[(b'priority', b'Priority')], max_length=255),
        ),
    ]
