# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-10-25 02:25
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0008_auto_20171024_1239'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='is_local',
        ),
        migrations.AddField(
            model_name='order',
            name='datetime_shipped',
            field=models.DateTimeField(null=True),
        ),
        migrations.AlterField(
            model_name='order',
            name='order_status',
            field=models.CharField(choices=[(b'waiting to be shipped', b'Waiting to be shipped'), (b'in progress', b'In progress'), (b'waiting for pharmacy partner', b'Waiting for pharmacy partner'), (b'shipped', b'Shipped'), (b'problem', b'Problem'), (b'fulfilled', b'Fulfilled'), (b'canceled', b'Canceled')], default=b'waiting to be shipped', max_length=255),
        ),
        migrations.AlterField(
            model_name='ordershipmententry',
            name='expiration',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='ordershipmententry',
            name='inventory_identifier',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AlterField(
            model_name='ordershipmententry',
            name='product',
            field=models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, related_name='shipment_entries', to='products.ProductType'),
        ),
    ]
