# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-10-26 21:49
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('dropdowns', '0015_orderproblemcategory'),
        ('orders', '0010_auto_20171025_1641'),
    ]

    operations = [
        migrations.CreateModel(
            name='OrderProblem',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.TextField()),
                ('added_datetime', models.DateTimeField(auto_now_add=True)),
                ('is_resolved', models.BooleanField(default=False)),
                ('added_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='order_problems', to=settings.AUTH_USER_MODEL)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to='dropdowns.OrderProblemCategory')),
            ],
        ),
        migrations.RemoveField(
            model_name='order',
            name='problem_category',
        ),
        migrations.RemoveField(
            model_name='order',
            name='problem_description',
        ),
        migrations.AddField(
            model_name='orderproblem',
            name='order',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='problems', to='orders.Order'),
        ),
    ]
