# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-10-29 05:07
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0011_auto_20171026_1649'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ordershipment',
            name='pharmacy_partner',
        ),
    ]
