# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-10-29 22:44
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('pharmacy', '0001_initial'),
        ('orders', '0012_remove_ordershipment_pharmacy_partner'),
    ]

    operations = [
        migrations.AddField(
            model_name='ordershipment',
            name='pharmacy_partner',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='shipments', to='pharmacy.PharmacyPartner'),
        ),
    ]
