# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-10-30 20:20
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0014_auto_20171029_1851'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='order_status',
            field=models.CharField(choices=[(b'on hold', b'Being prepared'), (b'waiting to be shipped', b'Waiting to be shipped'), (b'in progress', b'In progress'), (b'waiting for pharmacy partner', b'Waiting for pharmacy partner'), (b'partially_shipped', b'Partially Shipped'), (b'shipped', b'Shipped'), (b'problem', b'Problem'), (b'fulfilled', b'Fulfilled'), (b'canceled', b'Canceled')], default=b'waiting to be shipped', max_length=255),
        ),
    ]
