# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-10-30 20:57
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('pharmacy', '0001_initial'),
        ('orders', '0015_auto_20171030_1520'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='fulfilled_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='orders_to_fulfill', to='pharmacy.PharmacyPartner'),
        ),
    ]
