# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-10-31 04:38
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('orders', '0017_auto_20171030_1831'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='hold_datetime',
            field=models.DateTimeField(null=True),
        ),
        migrations.AddField(
            model_name='order',
            name='hold_reason',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='order',
            name='hold_requested_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='+', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='order',
            name='order_status',
            field=models.CharField(choices=[(b'on hold', b'On Hold'), (b'waiting to be shipped', b'Waiting to be shipped'), (b'in progress', b'In progress'), (b'waiting for pharmacy partner', b'Waiting for pharmacy partner'), (b'partially_shipped', b'Partially Shipped'), (b'shipped', b'Shipped'), (b'problem', b'Problem'), (b'fulfilled', b'Fulfilled'), (b'canceled', b'Canceled')], default=b'waiting to be shipped', max_length=255),
        ),
    ]
