# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-10-31 15:41
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0019_auto_20171031_1009'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='order_notes',
            field=models.TextField(default=''),
            preserve_default=False,
        ),
    ]
