# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-10-31 17:10
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0021_order_delivery_priority'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='order_origin',
            field=models.CharField(choices=[(b'account creation', b'Account Creation'), (b'manual', b'Manually Ordered'), (b'automatic refill', b'Automatic Refill'), (b'bulk order', b'Bulk Order'), (b'batch import', b'Batch Import')], max_length=255),
        ),
        migrations.AlterField(
            model_name='ordershipment',
            name='shipped_date',
            field=models.DateField(auto_now_add=True, default=datetime.datetime(2017, 10, 31, 17, 10, 24, 68000, tzinfo=utc)),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='ordershipmententry',
            name='quantity',
            field=models.PositiveIntegerField(blank=True, default=1),
        ),
    ]
