# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-10-31 19:06
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('orders', '0022_auto_20171031_1210'),
    ]

    operations = [
        migrations.AddField(
            model_name='orderproblem',
            name='resolved_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='resolved_problems', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='orderproblem',
            name='resolved_datetime',
            field=models.DateTimeField(null=True),
        ),
        migrations.AddField(
            model_name='orderproblem',
            name='resolved_description',
            field=models.TextField(default=''),
            preserve_default=False,
        ),
    ]
