# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-11-08 02:06
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0023_auto_20171031_1406'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='is_refill',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='order',
            name='order_notes',
            field=models.TextField(blank=True),
        ),
    ]
