# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-11-08 02:43
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0024_auto_20171107_2006'),
    ]

    operations = [
        migrations.AddField(
            model_name='ordercategory',
            name='is_refill',
            field=models.BooleanField(default=False),
        ),
    ]
