# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-11-08 02:44
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0025_ordercategory_is_refill'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='is_refill',
        ),
    ]
