# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-11-08 03:20
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0026_remove_order_is_refill'),
    ]

    operations = [
        migrations.CreateModel(
            name='ShippingClass',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, unique=True)),
                ('stamps_abbreviation', models.CharField(choices=[(b'US-FC', b'US-FC'), (b'US-PM', b'US-PM'), (b'US-XM', b'US-XM'), (b'US-MM', b'US-MM'), (b'US-PS', b'US-PS'), (b'US-LM', b'US-LM')], max_length=255, unique=True)),
            ],
        ),
        migrations.RemoveField(
            model_name='ordershipment',
            name='shipping_class',
        ),
    ]
