# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-11-08 03:20
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0027_auto_20171107_2120'),
    ]

    operations = [
        migrations.AddField(
            model_name='ordershipment',
            name='shipping_class',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='orders.ShippingClass'),
        ),
    ]
