# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-11-12 18:07
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0028_ordershipment_shipping_class'),
    ]

    operations = [
        migrations.CreateModel(
            name='ShippingPackageType',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, unique=True)),
            ],
        ),
    ]
