# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-11-13 00:43
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0031_auto_20171112_1842'),
    ]

    operations = [
        migrations.AddField(
            model_name='ordershipment',
            name='is_finalized',
            field=models.BooleanField(default=False),
        ),
    ]
