# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-11-15 14:38
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0033_auto_20171115_0835'),
    ]

    operations = [
        migrations.DeleteModel(
            name='DeliveryPriority',
        ),
    ]
