# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-11-24 17:43
from __future__ import unicode_literals

from django.db import migrations


def create_package_types(apps, schema_editor):
    types = [
        'Postcard',
        'Letter',
        'Large Envelope or Flat',
        'Thick Envelope',
        'Package',
        'Small Flat Rate Box',
        'Flat Rate Box',
        'Flat Rate Envelope',
        'Flat Rate Padded Envelope',
        'Large Package',
        'Oversized Package',
        'Regional Rate Box A',
        'Regional Rate Box B',
        'Regional Rate Box C',
        'Legal Flat Rate Envelope',
    ]

    ShippingPackageType = apps.get_model('orders', 'ShippingPackageType')
    for name in types:
        ShippingPackageType.objects.create(name=name)


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0037_auto_20171124_1143'),
    ]

    operations = [
        migrations.RunPython(create_package_types)
    ]
