# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2018-12-06 02:02
from __future__ import unicode_literals

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0038_auto_20171124_1143'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='datetime_added',
            field=models.DateTimeField(default=django.utils.timezone.localtime),
        ),
    ]
