# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2018-12-11 17:58
from __future__ import unicode_literals

from django.db import migrations


def ensure_unique_tracking_numbers(apps, schema_editor):
    OrderShipment = apps.get_model("orders", "OrderShipment")
    for shipment in OrderShipment.objects.all():
        tracking_number = shipment.tracking_number
        new_tracking_number = tracking_number
        if OrderShipment.objects.filter(
                tracking_number=tracking_number).count() >= 2:
            while True:
                new_tracking_number += "0"
                if OrderShipment.objects.filter(
                        tracking_number=new_tracking_number).count() == 0:
                    shipment.tracking_number = new_tracking_number
                    shipment.save()
                    break


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0039_auto_20181205_2002'),
    ]

    operations = [
        migrations.RunPython(ensure_unique_tracking_numbers)
    ]
