# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2018-12-11 18:04
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0040_auto_20181211_1158'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ordershipment',
            name='tracking_number',
            field=models.CharField(max_length=255, unique=True),
        ),
    ]
