# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2018-12-17 01:28
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0041_auto_20181211_1204'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ordershipment',
            name='tracking_number',
            field=models.CharField(max_length=255, null=True, unique=True),
        ),
    ]
