# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2018-12-18 00:12
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0042_auto_20181216_1928'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ordershipment',
            name='tracking_number',
            field=models.CharField(max_length=255, null=True),
        ),
    ]
