# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2019-01-28 05:04
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0046_auto_20190127_2237'),
    ]

    operations = [
        migrations.AddField(
            model_name='ordershipment',
            name='weight_ounces',
            field=models.FloatField(null=True),
        ),
        migrations.AddField(
            model_name='ordershipment',
            name='weight_pounds',
            field=models.FloatField(null=True),
        ),
    ]
