# Generated by Django 3.0.5 on 2020-06-01 04:44

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('pharmacy', '0003_auto_20180728_0741'),
        ('orders', '0048_auto_20190227_0543'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='added_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='orders_added', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='order',
            name='canceled_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='order',
            name='category',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='orders.OrderCategory'),
        ),
        migrations.AlterField(
            model_name='order',
            name='delivery_priority',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='orders.ShippingClass'),
        ),
        migrations.AlterField(
            model_name='order',
            name='fulfilled_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='orders_to_fulfill', to='pharmacy.PharmacyPartner'),
        ),
        migrations.AlterField(
            model_name='order',
            name='hold_requested_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='order',
            name='locked_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='locked_orders', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='order',
            name='order_origin',
            field=models.CharField(choices=[('account creation', 'Account Creation'), ('manual', 'Manually Ordered'), ('automatic refill', 'Automatic Refill'), ('bulk order', 'Bulk Order'), ('batch import', 'Batch Import')], max_length=255),
        ),
        migrations.AlterField(
            model_name='order',
            name='order_status',
            field=models.CharField(choices=[('on hold', 'On Hold'), ('waiting to be shipped', 'Waiting to be shipped'), ('in progress', 'In progress'), ('waiting for pharmacy partner', 'Waiting for pharmacy partner'), ('partially_shipped', 'Partially Shipped'), ('shipped', 'Shipped'), ('problem', 'Problem'), ('fulfilled', 'Fulfilled'), ('canceled', 'Canceled')], default='waiting to be shipped', max_length=255),
        ),
        migrations.AlterField(
            model_name='order',
            name='order_type',
            field=models.CharField(choices=[('patient', 'Patient'), ('bulk', 'Bulk')], max_length=255),
        ),
        migrations.AlterField(
            model_name='order',
            name='patient',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='orders', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='order',
            name='rx_partner',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='orders', to='pharmacy.PharmacyPartner'),
        ),
        migrations.AlterField(
            model_name='orderproblem',
            name='added_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='order_problems', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='orderproblem',
            name='resolved_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='resolved_problems', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='ordershipment',
            name='package_type',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='orders.ShippingPackageType'),
        ),
        migrations.AlterField(
            model_name='ordershipment',
            name='packed_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='order_shipments_packed', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='ordershipment',
            name='pharmacy_partner',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='shipments', to='pharmacy.PharmacyPartner'),
        ),
        migrations.AlterField(
            model_name='ordershipment',
            name='ship_vendor',
            field=models.CharField(choices=[('ups', 'UPS')], max_length=255),
        ),
        migrations.AlterField(
            model_name='ordershipment',
            name='shipped_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='orders_shipped', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='ordershipment',
            name='shipping_class',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='orders.ShippingClass'),
        ),
        migrations.AlterField(
            model_name='shippingclass',
            name='stamps_abbreviation',
            field=models.CharField(blank=True, choices=[('US-FC', 'US-FC'), ('US-PM', 'US-PM'), ('US-XM', 'US-XM'), ('US-MM', 'US-MM'), ('US-PS', 'US-PS'), ('US-LM', 'US-LM')], max_length=255, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='shippingpackagetype',
            name='name',
            field=models.CharField(choices=[('Postcard', 'Postcard'), ('Letter', 'Letter'), ('Large Envelope or Flat', 'Large Envelope or Flat'), ('Thick Envelope', 'Thick Envelope'), ('Package', 'Package'), ('Small Flat Rate Box', 'Small Flat Rate Box'), ('Flat Rate Box', 'Flat Rate Box'), ('Flat Rate Envelope', 'Flat Rate Envelope'), ('Flat Rate Padded Envelope', 'Flat Rate Padded Envelope'), ('Large Package', 'Large Package'), ('Oversized Package', 'Oversized Package'), ('Regional Rate Box A', 'Regional Rate Box A'), ('Regional Rate Box B', 'Regional Rate Box B'), ('Regional Rate Box C', 'Regional Rate Box C'), ('Legal Flat Rate Envelope', 'Legal Flat Rate Envelope')], max_length=255, unique=True),
        ),
    ]
