# Generated by Django 3.0.8 on 2020-08-31 00:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mobile', '0005_auto_20200830_1659'),
    ]

    operations = [
        migrations.AddField(
            model_name='mobilenotification',
            name='subject',
            field=models.TextField(default=''),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='mobilenotification',
            name='is_pushed',
            field=models.BooleanField(default=False, editable=False),
        ),
    ]
