# Generated by Django 3.0.8 on 2020-09-03 15:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('mobile', '0006_auto_20200830_1913'),
    ]

    operations = [
        migrations.CreateModel(
            name='MobileNotificationQuestion',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, unique=True)),
                ('text', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='MobileNotificationQuestionAnswer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.CharField(max_length=255)),
                ('question', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='possible_answers', to='mobile.MobileNotificationQuestion')),
            ],
        ),
        migrations.CreateModel(
            name='MobileNotificationQuestionEntry',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ordering', models.PositiveIntegerField()),
                ('answer', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='mobile.MobileNotificationQuestionAnswer')),
                ('notification', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='question_entries', to='mobile.MobileNotification')),
                ('question', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to='mobile.MobileNotificationQuestion')),
            ],
            options={
                'ordering': ['ordering'],
            },
        ),
    ]
