# Generated by Django 3.0.8 on 2020-09-27 17:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mobile', '0007_mobilenotificationquestion_mobilenotificationquestionanswer_mobilenotificationquestionentry'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mobilenotificationquestionentry',
            name='ordering',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
