from django.conf.urls import include, url
from django.views.generic import TemplateView

from genesishealth.apps.utils.views import generic_dashboard
from genesishealth.apps.accounts.views import groups as views


id_urlpatterns = [
    url(r'^patients/',
        include('genesishealth.apps.accounts.urls.groups.patients')),
    url(r'^professionals/',
        include('genesishealth.apps.accounts.urls.groups.professionals')),
    url(r'^payors/',
        include('genesishealth.apps.accounts.urls.groups.payors')),
    url(r'^companies/',
        include('genesishealth.apps.accounts.urls.groups.companies')),
    url(r'^devices/',
        include('genesishealth.apps.accounts.urls.groups.devices')),
    url(r'^demo/',
        include('genesishealth.apps.accounts.urls.groups.demo')),
    url(r'^communications/$',
        views.communications,
        name='groups-communications')
]

urlpatterns = [
    url(r'^$',
        views.main,
        name='manage-groups'),
    url(r'^new/$',
        views.add,
        name='manage-groups-create'),
    url(r'^new/thanks/$',
        generic_dashboard,
        {'title': 'Create Group',
         'content': 'The group has been created.'},
        name='manage-groups-create-thanks'),
    url(r'^import/$',
        views.import_group,
        name='manage-groups-import'),
    url(r'^(?P<group_id>\d+?)/$',
        views.edit,
        name='manage-groups-edit'),
    url(r'^edit/$',
        views.edit,
        name='manage-groups-professional-edit'),
    url(r'^(?P<group_id>\d+?)/reports/$',
        views.reports,
        name='manage-groups-reports'),
    url(r'^(?P<group_id>\d+?)/generate_participation_report/$',
        views.participation_report,
        name='manage-groups-participation-report'),
    url(r'^(?P<group_id>\d+?)/generate_participation_status_report/$',
        views.participation_status_report,
        name='manage-groups-participation-status-report'),
    url(r'^(?P<group_id>\d+?)/generate_inactive_participation_status_report/$',
        views.inactive_participation_status_report,
        name='manage-groups-inactive-participation-status-report'),
    url(r'^(?P<group_id>\d+?)/generate_noncompliant_report/$',
        views.noncompliant_report,
        name='manage-groups-noncompliant-report'),
    url(r'^(?P<group_id>\d+?)/generate_target_range_report/$',
        views.target_range_report,
        name='manage-groups-target-range-report'),
    url(r'^edit/thanks/$',
        TemplateView.as_view(
            template_name='accounts/manage/edit-group-thanks.html'),
        name='manage-groups-edit-thanks'),
    url(r'^(?P<group_id>\d+?)/detail/$',
        views.group_detail,
        name='manage-groups-detail'),
    url(r'^(?P<group_id>\d+?)/export/$',
        views.group_export,
        name='manage-groups-export'),
    url(r'^(?P<group_id>\d+?)/export_accounts/$',
        views.group_export_accounts,
        name='manage-groups-export-accounts'),
    url(r'^(?P<group_id>\d+?)/export_account_status/$',
        views.group_account_status,
        name='manage-groups-account-status-report'),
    url(r'^(?P<group_id>\d+)/reading_delay_report/$',
        views.group_reading_delay_report,
        name='manage-groups-reading-delay-report'),
    url(r'(?P<group_id>\d+?)/',
        include(id_urlpatterns)),
]
