# Generated by Django 3.0.5 on 2020-06-01 04:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('heartbeat', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='endtoendrecord',
            name='result',
            field=models.CharField(choices=[('success', 'Success'), ('failure', 'Failure'), ('warning', 'Warning')], max_length=255),
        ),
    ]
