# Generated by Django 3.0.5 on 2020-06-01 04:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contact', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contactformsubmission',
            name='content',
            field=models.TextField(verbose_name='Message'),
        ),
    ]
