# Generated by Django 3.0.8 on 2020-07-13 12:22

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='WorkQueueItem',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('datetime_added', models.DateTimeField(auto_now_add=True)),
                ('name', models.CharField(max_length=255)),
                ('item_type', models.CharField(choices=[('Order', 'Order'), ('Report', 'Report')], max_length=255)),
                ('is_passed_qa', models.BooleanField(default=False)),
            ],
        ),
    ]
