# Generated by Django 3.0.8 on 2020-07-13 12:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('work_queue', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='workqueueitem',
            name='status',
            field=models.CharField(choices=[('In QA', 'In QA'), ('Ready to Work', 'Ready to Work')], default='In QA', max_length=255),
        ),
    ]
