# Generated by Django 3.0.8 on 2020-07-13 12:51

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('work_queue', '0002_workqueueitem_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='workqueueitem',
            name='datetime_due',
            field=models.DateTimeField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
