# Generated by Django 3.0.8 on 2020-07-24 04:28

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('work_queue', '0003_workqueueitem_datetime_due'),
    ]

    operations = [
        migrations.CreateModel(
            name='WorkQueueType',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='WorkQueueProfile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('allowed_types', models.ManyToManyField(related_name='_workqueueprofile_allowed_types_+', to='work_queue.WorkQueueType')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='work_queue_profile', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
