# Generated by Django 3.0.8 on 2020-07-24 04:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('work_queue', '0004_workqueueprofile_workqueuetype'),
    ]

    operations = [
        migrations.AlterField(
            model_name='workqueueitem',
            name='item_type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to='work_queue.WorkQueueType'),
        ),
    ]
