# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2018-07-16 16:13
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('pharmacy', '0002_auto_20171120_1816'),
        ('accounts', '0058_auto_20180607_1315'),
    ]

    operations = [
        migrations.CreateModel(
            name='EPCAPIUser',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, unique=True)),
                ('username', models.CharField(max_length=255, unique=True)),
                ('password', models.CharField(max_length=255)),
                ('is_active', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='EPCGroup',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('identifier', models.CharField(max_length=255, unique=True)),
                ('is_active', models.BooleanField(default=True)),
                ('company', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='epc_group_identifier', to='accounts.Company')),
            ],
        ),
        migrations.CreateModel(
            name='EPCNursingGroup',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, unique=True)),
                ('identifier', models.CharField(max_length=255, unique=True)),
                ('is_active', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='EPCPharmacy',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('identifier', models.CharField(max_length=255, unique=True)),
                ('is_active', models.BooleanField(default=True)),
                ('pharmacy', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='epc_pharmacy_identifier', to='pharmacy.PharmacyPartner')),
            ],
        ),
        migrations.CreateModel(
            name='PatientRequestTransaction',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('datetime_added', models.DateTimeField(auto_now_add=True)),
                ('submitted_username', models.CharField(max_length=255, null=True)),
                ('raw_request', models.TextField()),
                ('transaction_identifier', models.CharField(max_length=255, null=True)),
                ('transaction_type', models.CharField(choices=[(b'original', b'original'), (b'update', b'update')], max_length=255, null=True)),
                ('epc_member_identifier', models.CharField(max_length=255)),
                ('group_identifier_raw', models.CharField(max_length=255, null=True)),
                ('fulfillment_identifier_raw', models.CharField(max_length=255, null=True)),
                ('nursing_identifier_raw', models.CharField(max_length=255, null=True)),
                ('first_name', models.CharField(max_length=255, null=True)),
                ('last_name', models.CharField(max_length=255, null=True)),
                ('address1', models.CharField(max_length=255, null=True)),
                ('address2', models.CharField(max_length=255, null=True)),
                ('city', models.CharField(max_length=255, null=True)),
                ('state', models.CharField(max_length=255, null=True)),
                ('zipcode', models.CharField(max_length=255, null=True)),
                ('phone', models.CharField(max_length=255, null=True)),
                ('date_of_birth', models.DateField(null=True)),
                ('email_address', models.CharField(max_length=255, null=True)),
                ('is_successful', models.BooleanField()),
                ('authenticated_user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='patient_transactions', to='epc.EPCAPIUser')),
                ('fulfillment_identifier', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='epc.EPCPharmacy')),
                ('group_identifier', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='epc.EPCGroup')),
                ('nursing_identifier', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='epc.EPCNursingGroup')),
            ],
        ),
    ]
