# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2018-07-17 01:49
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('epc', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='EPCMemberProfile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('identifier', models.CharField(max_length=255, unique=True)),
                ('patient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='epc_member_profiles', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='OrderRequestTransaction',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('datetime_added', models.DateTimeField(auto_now_add=True)),
                ('submitted_username', models.CharField(max_length=255, null=True)),
                ('raw_request', models.TextField()),
                ('transaction_identifier', models.CharField(max_length=255, null=True)),
                ('transaction_type', models.CharField(choices=[(b'original', b'original'), (b'update', b'update')], max_length=255, null=True)),
                ('epc_member_identifier', models.CharField(max_length=255, null=True)),
                ('order_number', models.CharField(max_length=255, null=True)),
                ('order_type', models.CharField(max_length=255, null=True)),
                ('order_method', models.CharField(max_length=255, null=True)),
                ('order_date', models.DateField(null=True)),
                ('meter_request', models.IntegerField(null=True)),
                ('strips_request', models.IntegerField(null=True)),
                ('lancet_request', models.IntegerField(null=True)),
                ('lancing_device_request', models.IntegerField(null=True)),
                ('pamphlet_id_request', models.IntegerField(null=True)),
                ('meter_shipped', models.IntegerField(null=True)),
                ('meid', models.CharField(max_length=255, null=True)),
                ('strips_shipped', models.IntegerField(null=True)),
                ('lancets_shipped', models.IntegerField(null=True)),
                ('control_solution_shipped', models.IntegerField(null=True)),
                ('lancing_device_shipped', models.IntegerField(null=True)),
                ('pamphlet_id_shipped', models.IntegerField(null=True)),
                ('order_status', models.CharField(max_length=255, null=True)),
                ('ship_date', models.DateField(null=True)),
                ('tracking_number', models.CharField(max_length=255, null=True)),
                ('is_successful', models.BooleanField()),
                ('authenticated_user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='order_transactions', to='epc.EPCAPIUser')),
                ('epc_member', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='order_request_transactions', to='epc.EPCMemberProfile')),
            ],
        ),
    ]
