# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2018-07-17 02:59
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('epc', '0002_epcmemberprofile_orderrequesttransaction'),
    ]

    operations = [
        migrations.AddField(
            model_name='patientrequesttransaction',
            name='epc_member',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='patient_request_transactions', to='epc.EPCMemberProfile'),
        ),
    ]
