# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2018-07-26 14:19
from __future__ import unicode_literals

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('epc', '0007_auto_20180726_0912'),
    ]

    operations = [
        migrations.AlterField(
            model_name='patientrequesttransaction',
            name='datetime_added',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
