# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2018-07-28 13:29
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('epc', '0008_auto_20180726_0919'),
        ('nursing', '0001_initial')
    ]

    operations = [
        migrations.AlterField(
            model_name='patientrequesttransaction',
            name='fulfillment_identifier',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='pharmacy.PharmacyPartner'),
        ),
        migrations.AlterField(
            model_name='patientrequesttransaction',
            name='nursing_identifier',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='nursing.NursingGroup'),
        ),
    ]
