# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2018-07-27 18:05
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('epc', '0010_auto_20180727_1140'),
    ]

    operations = [
        migrations.CreateModel(
            name='EPCOrderNote',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('message', models.TextField()),
                ('added_datetime', models.DateTimeField(default=django.utils.timezone.now)),
                ('ordering', models.PositiveIntegerField()),
                ('added_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='epc_order_notes', to=settings.AUTH_USER_MODEL)),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notes', to='epc.EPCOrder')),
            ],
        ),
        migrations.AddField(
            model_name='epcorderchange',
            name='ordering',
            field=models.PositiveIntegerField(default=None),
            preserve_default=False,
        ),
        migrations.AlterUniqueTogether(
            name='epcorderchange',
            unique_together=set([('ordering', 'order')]),
        ),
        migrations.AddField(
            model_name='epcordernote',
            name='order_change',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='note', to='epc.EPCOrderChange'),
        ),
        migrations.AlterUniqueTogether(
            name='epcordernote',
            unique_together=set([('order', 'ordering')]),
        ),
    ]
