# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2018-07-27 19:38
from __future__ import unicode_literals

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('epc', '0011_auto_20180727_1305'),
    ]

    operations = [
        migrations.AlterField(
            model_name='epcorder',
            name='datetime_added',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='epcorderchange',
            name='datetime_added',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
