# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2018-07-31 06:21
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('nursing', '0001_initial'),
        ('pharmacy', '0003_auto_20180728_0741'),
        ('accounts', '0058_auto_20180607_1315'),
        ('epc', '0012_auto_20180727_1438'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='epcgroup',
            name='company',
        ),
        migrations.DeleteModel(
            name='EPCNursingGroup',
        ),
        migrations.RemoveField(
            model_name='epcpharmacy',
            name='pharmacy',
        ),
        migrations.AddField(
            model_name='epcmemberprofile',
            name='company',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='accounts.Company'),
        ),
        migrations.AddField(
            model_name='epcmemberprofile',
            name='creating_transaction',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='epc.PatientRequestTransaction'),
        ),
        migrations.AddField(
            model_name='epcmemberprofile',
            name='nursing_group',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='nursing.NursingGroup'),
        ),
        migrations.AddField(
            model_name='epcmemberprofile',
            name='pharmacy_partner',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='pharmacy.PharmacyPartner'),
        ),
        migrations.AlterField(
            model_name='patientrequesttransaction',
            name='group_identifier',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='accounts.Company'),
        ),
        migrations.DeleteModel(
            name='EPCGroup',
        ),
        migrations.DeleteModel(
            name='EPCPharmacy',
        ),
    ]
