# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2018-07-28 23:05
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('epc', '0013_auto_20180731_0121'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='epcmemberprofile',
            name='company',
        ),
        migrations.RemoveField(
            model_name='epcmemberprofile',
            name='creating_transaction',
        ),
        migrations.RemoveField(
            model_name='epcmemberprofile',
            name='nursing_group',
        ),
        migrations.RemoveField(
            model_name='epcmemberprofile',
            name='patient',
        ),
        migrations.RemoveField(
            model_name='epcmemberprofile',
            name='pharmacy_partner',
        ),
        migrations.AlterModelOptions(
            name='epcordernote',
            options={'ordering': ('-ordering',)},
        ),
        migrations.AlterField(
            model_name='epcorder',
            name='epc_member',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='epc_orders', to='accounts.PatientProfile'),
        ),
        migrations.AlterField(
            model_name='epcorderchange',
            name='epc_member',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='epc_order_changes', to='accounts.PatientProfile'),
        ),
        migrations.AlterField(
            model_name='orderrequesttransaction',
            name='epc_member',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='order_request_transactions', to='accounts.PatientProfile'),
        ),
        migrations.AlterField(
            model_name='patientrequesttransaction',
            name='epc_member',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='patient_request_transactions', to='accounts.PatientProfile'),
        ),
        migrations.DeleteModel(
            name='EPCMemberProfile',
        ),
    ]
