# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2018-08-01 16:46
from __future__ import unicode_literals

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('epc', '0014_auto_20180728_1805'),
    ]

    operations = [
        migrations.CreateModel(
            name='EPCLogEntry',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('datetime_added', models.DateTimeField(default=django.utils.timezone.now)),
                ('is_successful', models.BooleanField()),
                ('content', models.TextField()),
                ('source', models.CharField(max_length=255)),
                ('transaction_type', models.CharField(choices=[(b'order', b'Order'), (b'patient', b'Patient')], max_length=255)),
                ('response_sent', models.CharField(max_length=255)),
            ],
        ),
    ]
