# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2018-08-02 19:58
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('epc', '0017_auto_20180802_1453'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orderrequesttransaction',
            name='log_entry',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='order_transaction', to='epc.EPCLogEntry'),
        ),
        migrations.AlterField(
            model_name='patientrequesttransaction',
            name='log_entry',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='patient_transaction', to='epc.EPCLogEntry'),
        ),
    ]
