# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2018-08-02 21:41
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0064_company_nursing_group'),
        ('epc', '0018_auto_20180802_1458'),
    ]

    operations = [
        migrations.AddField(
            model_name='epclogentry',
            name='epc_member',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='accounts.PatientProfile'),
        ),
    ]
