# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2019-02-08 00:22
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0047_auto_20190127_2304'),
        ('epc', '0019_epclogentry_epc_member'),
    ]

    operations = [
        migrations.AddField(
            model_name='epcorder',
            name='order',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='epc_orders', to='orders.Order'),
        ),
    ]
