from django.conf.urls import include, url
from django.contrib.auth.decorators import login_required
from django.views.generic import TemplateView

from genesishealth.apps.accounts.forms.main import AuthenticationForm
from genesishealth.apps.utils.views import generic_dashboard

from genesishealth.apps.accounts.views import groups as group_views
from genesishealth.apps.accounts.views import main as main_views


urlpatterns = [
    url(r'^login/$',
        main_views.custom_login,
        {'template_name': 'accounts/login.html',
         'authentication_form': AuthenticationForm},
        name='login'),
    url(r'^setup_security/$',
        main_views.setup_security,
        name='setup-security'),
    url(r'^reset_password/finish/$',
        main_views.reset_password_finish,
        name='reset-password-finish'),
    url(r'^logout/$',
        main_views.logout,
        {'template_name': 'accounts/logout.html'},
        name='logout'),
    url(r'^update_password/$',
        main_views.update_password,
        name='update-password'),
    url(r'^password_expired/$',
        main_views.update_password_expired,
        name='update-password-expired'),
    url(r'^manage_login/(?P<user_id>\d+?)/$',
        main_views.manage_login,
        name='manage-login'),
    url(r'^reset_password/(?P<user_id>\d+?)/$',
        main_views.reset_password_confirm,
        name='reset-password-confirm'),
    url(r'^update_email/$',
        main_views.update_email,
        name='update-email'),
    url(r'^lost_password/$',
        main_views.lost_password,
        name='lost-password'),
    url(r'^retrieve_username/$',
        main_views.retrieve_username,
        name='retrieve-username'),
    url(r'^reset/thanks/$',
        TemplateView.as_view(
            template_name='accounts/reset_thanks.html'),
        name='reset-password-thanks'),
    url(r'^reset/(?P<forgot_hash>\w+)/$',
        main_views.reset_password,
        name='reset-password'),
    url(r'^users/$',
        main_views.users,
        name='manage-users'),
    url(r'^profile/$',
        main_views.my_profile,
        name='profile'),
    url(r'^security_questions/$',
        main_views.security_questions,
        name='security-questions'),
    url(r'^accept-terms/$',
        main_views.accept_terms,
        name='accept-terms'),
    url(r'^accept-privacy/$',
        main_views.accept_privacy,
        name='accept-privacy'),
    url(r'^communications/$',
        main_views.communications,
        name='communications'),
    url(r'^communications/configure_resolution_report/$',
        main_views.configure_communications_resolution_report,
        name='configure-communications-resolution-report'),
    url(r'^communications/resolution_report/$',
        main_views.communications_resolution_report,
        name='communications-resolution-report'),
    url(r'^communications/resolution_report_print/$',
        main_views.communications_resolution_report_print,
        name='communications-resolution-report-print'),
    url(r'^communications/resolution_report_pdf/$',
        main_views.communications_resolution_report_pdf,
        name='communications-resolution-report-pdf'),
    url(r'^communications/call_log_report/$',
        main_views.configure_call_log_report,
        name='configure-call-log-report'),
    url(r'^communications/call_log/$',
        main_views.call_log_report,
        name='call-log-report'),
    url(r'^communications/call_log_print/$',
        main_views.call_log_report_print,
        name='call-log-report-print'),
    url(r'^communications/call_log_pdf/$',
        main_views.call_log_report_pdf,
        name='call-log-report-pdf'),
    url(r'^groups/',
        include('genesishealth.apps.accounts.urls.groups')),
    url(r'^patients/',
        include('genesishealth.apps.accounts.urls.patients')),
    url(r'^professionals/',
        include('genesishealth.apps.accounts.urls.professionals')),
    url(r'^payors/',
        include('genesishealth.apps.accounts.urls.payors')),
    url(r'^companies/',
        include('genesishealth.apps.accounts.urls.companies')),
    url(r'^demo/',
        include('genesishealth.apps.accounts.urls.demo')),
]


urlpatterns += [
    url(r'^group/$',
        group_views.edit,
        name='manage-my-group'),
    url(r'^group/thanks/$',
        generic_dashboard,
        {'title': 'Edit Group',
         'content': 'Your group has been updated.'},
        name='manage-my-group-thanks'),
]
