# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2019-04-13 16:33
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('text_messaging', '0002_textmessagelogentry'),
    ]

    operations = [
        migrations.AddField(
            model_name='textmessagingconfiguration',
            name='body_password',
            field=models.CharField(default='', max_length=255),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='textmessagingconfiguration',
            name='body_username',
            field=models.CharField(default='', max_length=255),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='textmessagingconfiguration',
            name='header_password',
            field=models.CharField(default='', max_length=255),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='textmessagingconfiguration',
            name='header_username',
            field=models.CharField(default='', max_length=255),
            preserve_default=False,
        ),
    ]
