# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2019-04-13 16:45
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('text_messaging', '0003_auto_20190413_1133'),
    ]

    operations = [
        migrations.AddField(
            model_name='textmessagingconfiguration',
            name='end_point_url_base',
            field=models.CharField(default='', max_length=255),
            preserve_default=False,
        ),
    ]
