# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2019-04-13 20:16
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('text_messaging', '0005_textmessagingconfiguration_verify_ssl'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='textmessagelogentry',
            name='phone_number',
        ),
        migrations.RemoveField(
            model_name='textmessagelogentry',
            name='recipient',
        ),
        migrations.AddField(
            model_name='textmessagelogentry',
            name='recipients',
            field=models.ManyToManyField(related_name='text_message_log_entries', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='textmessagelogentry',
            name='request_payload',
            field=models.TextField(default=''),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='textmessagelogentry',
            name='response_content',
            field=models.TextField(default=''),
            preserve_default=False,
        ),
    ]
