# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2019-04-13 21:51
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('text_messaging', '0006_auto_20190413_1516'),
    ]

    operations = [
        migrations.AddField(
            model_name='textmessagingconfiguration',
            name='is_qa_mode',
            field=models.BooleanField(default=True),
        ),
    ]
